<div class="box">
<?php echo $this->docMenu(); ?>
</div>
<div class="box">
Adresa: <?php echo $this->path($this->path, $this->directory); ?> <?php if ($this->directory->parent_id) echo $this->formButton("edit-directory", "Upravit adresář")?><br />
Pobočka: <strong>
<?php 
if ($this->directory->subsidiary_id) {
	foreach ($this->subsidiaries as $sub) {
		if ($sub->id_subsidiary == $this->directory->subsidiary_id) {
			echo $sub->subsidiary_name;
			break;
		}
	}
} else {
	echo "-";
}
?>
</strong>
<?php
// kontrola acl pro vytvoreni noveho adresare
$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();

if ($acl->isAllowed($user->role, "document:directory", "post")) {
	echo $this->formPostDir;
}

// kontrola ACL pro upload souboru
if ($acl->isAllowed($user->role, "document:document", "upload")) {
	echo $this->formPostFile;
	
	if ($acl->isAllowed($user->role, "document:directory", "multiupload"))
		echo $this->formLabel("multiupload", "Hromadné nahrávání: ") . $this->formCheckbox("multiupload", 1);
}

?>
</div>
<?php 

// kontrola ACL pro smazani adresare
$dirActions = array();

if ($acl->isAllowed($user->role, "document:directory", "delete")) {
	$dirActions["Smazat"] = $this->url(array("clientId" => $this->clientId, "directoryId" => "__DIR__"), "document-directory-delete");
}

// vypis adresaru a souboru
echo "<h1>Výpis adresáře</h1>";
echo "<h2>" . $this->directory->name . "</h2>";
?>
<table>
	<tbody>
<?php 
foreach ($this->childDirs as $dir) {
	echo "<tr><td><span class='directory'></span>";
	echo $this->path()->dirLink($dir, $dir->name);
	echo "</td>";
	echo "<td>";
	
	foreach ($dirActions as $label => $action) {
		$url = str_replace("__DIR__", $dir->id, $action);
		
		echo "<a href='$url' class='dettach'>$label</a>";
	}
	
	echo "</td></tr>";
}

foreach ($this->childDocuments as $file) {
	echo "<tr><td><span class='document'></span>";
	echo $this->file($file);
	echo "</td>";
	echo "<td>";

	// vyhodnoceni prav k souboru
	$fileActions = array();
	
	if ($acl->isAllowed($user->role, "document:directory", "detach") && ($file->user_id == $user->id_user || $acl->isAllowed($user->role, "document:directory", "editother"))) {
		$fileActions["Odebrat"] = $this->url(array("clientId" => $this->clientId, "directoryId" => "__DIR__", "fileId" => "__FILE__"), "document-directory-dettach");
	}
	
	// prepis akci a jejich zapis
	foreach ($fileActions as $label => $action) {
		$url = str_replace("__DIR__", $this->directory->id, $action);
		$url = str_replace("__FILE__", $file->id, $url);
		
		echo "<a href='$url' class='dettach'>$label</a>";
	}

	echo "</td></tr>";
}
?>
	</tbody>
</table>
<div class="hidden">
	<div id="form-edit-dir">
	<?php echo $this->formEdit; ?>
	</div>
</div>
<script type="text/javascript" src="/js/document/document.js"></script>