<h1>Úprava neshody</h1>
<?php 
echo $this->form;
echo $this->dataList("categories", $this->categories);
echo $this->dataList("subcategories", $this->subcategories);

// kontrola mazaciho formulare
if ($this->deleteForm) {
	echo "<h2>Smazat neshodu</h2>";
	echo $this->deleteForm;
}
?>
<h2>Podobné existující neshody</h2>
<table>
	<thead>
		<tr>
			<th>
			Kategorie
			</th>
			<th>
			Podkategorie
			</th>
			<th>
			Upřesnění
			</th>
			<th rowspan="2">
			Vybrat
			</th>
		</tr>
		<tr>
			<th colspan="3">
			Neshoda
			</th>
		</tr>
	</thead>
</table>
<script type="text/javascript" src="/js/audit/mistake/create.js"></script>