<script type="text/javascript">
var CLIENTID = <?php echo $this->client->id_client; ?>
</script>
<?php
echo $this->formButton("toggle-filter", "Zobrazit/skrýt filtraci");
echo $this->formFilter;
?>
<table id="mistake-list" class="multirow-table">
<?php 
echo $this->mistakeTable()->header();

$actions = array("show-mistake" => "Zobrazit");
$today = (int) Zend_Date::now()->get("yMMdd");

foreach ($this->mistakes as $mistake) {
	// vyhodnoceni trid
	$classes = array();

	if ($mistake->is_removed) {
		$classes[] = "mistake-removed";
	} elseif ($mistake->isMarked($today)) {
		$classes[] = "mistake-marked";
	}
	
	echo $this->mistakeTable()->mistake($mistake, array("actions" => $actions, "classes" => $classes));
}
?>
</table>
<?php 
$user = Zend_Auth::getInstance()->getIdentity();
$acl = new My_Controller_Helper_Acl();

if ($acl->isAllowed($user->role, "audit:mistake", "import")) {
?>
<h2>Import neshod</h2>
<em>Podporovaný formát je CSV s nastavením:
<ul>
	<li>Text uzavřen do uvozovek</li>
	<li>Položky odděleny čárkami</li>
	<li>Escapovací znak zpětné lomítko</li>
</ul></em>
<form action="<?php echo $this->url(array("clientId" => $this->client->id_client), "audit-mistake-import"); ?>" method="post" enctype="multipart/form-data">
	<p>
		<?php 
		echo $this->formLabel("importfile", "Soubor s neshodami");
		echo $this->formFile("importfile");
		?>
	</p>
	<p>
		<?php 
		$items = $this->formFilter->getElement("subsidiary_id")->getMultiOptions();
		$items[0] = "---Vyberte---";
		echo $this->formLabel("subsidiaryId", "Pobočka: ");
		echo $this->formSelect("subsidiaryId", null, null, $items);
		?>
	</p>
	<p>
	<?php 
	echo $this->formLabel("encoding", "Kódování souboru:");
	echo $this->formSelect("encoding", null, array(), array("CP1250" => "CP-1250 (windows)", "UTF8" => "UTF-8"))
	?>
	</p>
	<p>
		<?php echo $this->formSubmit("import-submit", "Importovat"); ?>
	</p>
</form>
<b>Pozor! při importu budou všechny stávající neshody, které nejsou vázány na audit smazány a nahrazeny novými!</b>
<?php 
}
?>
<script type="text/javascript" src="/js/audit/mistake/index.js"></script>