<?php
$user = Zend_Auth::getInstance()->getIdentity();
$acl = new My_Controller_Helper_Acl();

$clientId = $this->client->id_client;
?>
<script type="text/javascript">
var CLIENTID = <?php echo $this->client->id_client; ?>
</script>
<?php
if ($acl->isAllowed($user->role, "audit:mistake", "post")) {
	printf("<fieldset><legend>Nová neshoda</legend>%s</fieldset>", $this->formButton("new-mistake", "Přidat novou neshodu"));
}

$this->formFilter->setAction("#mistakes");

echo $this->showHidePanel($this->formFilter, "Filtrace", "Zobrazit/skrýt filtraci", true);

if (in_array($user->role, array(My_Role::ROLE_ADMIN, My_Role::ROLE_COORDINATOR))) {
    // vygenerovani tlacitka pro odkaz na XLS
    $parts = explode("?", $_SERVER["REQUEST_URI"]);
    $parts[0] .= ".xls";

    $xlsUrl = implode("?", $parts);

    printf("<p><form action='%s' target='_blank' method='post'><input type='submit' value='Stáhnout ve formátu MS Excel (beta)'></form></p>", $xlsUrl);
}
?>
<?php printf("<form action='/audit/mistake/submits?clientId=%s' method='post' onsubmit='return confirm(\"Provedené změny již nepůjdou vrátit zpět. Skutečně pokračovat?\")'>", $clientId); ?>
<table id="mistake-list" class="multirow-table">
<?php 
echo $this->mistakeTable()->header();

$actions = array("show-mistake" => "Zobrazit");

if ($acl->isAllowed($user->role, "audit:mistake", "edit")) {
	$actions["edit-mistake"] = "Editovat";
}

$selector = $acl->isAllowed($user->role, "audit:mistake", "submits");

$today = (int) Zend_Date::now()->get("yMMdd");

foreach ($this->mistakes as $mistake) {
	// vyhodnoceni trid
	$classes = array();

	if ($mistake->is_removed) {
		$classes[] = "mistake-removed";
	} elseif ($mistake->is_marked) {
		$classes[] = "mistake-marked";
	}
	
	echo $this->mistakeTable()->mistake($mistake, array("actions" => $actions, "classes" => $classes, "selector" => $selector, "subsidiaryRow" => $this->subsidiaryRow));
}
?>
</table>
<?php 
// dokonceni formulare pro hromadne odeslani neshod
if ($acl->isAllowed($user->role, "audit:mistake", "submits")) {
    printf("<div>%s</div>", $this->formSubmit("submit-all", "Označit jako odstraněné"));
}

echo "</form>";

if ($acl->isAllowed($user->role, "audit:mistake", "import")) {
?>
<fieldset>
    <legend>Import neshod</legend>
    <div><?php echo $this->formButton("display-import-mist", "Zobrazit/skrýt import neshod", array("onclick" => "$('#mistake-impdiv').toggle()")); ?></div>
    <div id="mistake-impdiv" style="display: none; ">
        <em>Podporovaný formát je CSV s nastavením:
        <ul>
            <li>Text uzavřen do uvozovek</li>
            <li>Položky odděleny čárkami</li>
            <li>Escapovací znak zpětné lomítko</li>
        </ul></em>
        <form action="<?php echo $this->url(array("clientId" => $this->client->id_client), "audit-mistake-import"); ?>" method="post" enctype="multipart/form-data">
            <p>
                <?php 
                echo $this->formLabel("importfile", "Soubor s neshodami");
                echo $this->formFile("importfile");
                ?>
            </p>
            <p>
                <?php 
                $items[0] = "---Vyberte---";
                
                foreach ($this->subsidiaries as $item) {
                    $items[$item->id_subsidiary] = $item->subsidiary_name . "(" . $item->subsidiary_town . " - " . $item->subsidiary_street . ")";
                }
                
                echo $this->formLabel("subsidiaryId", "Pobočka: ");
                echo $this->formSelect("subsidiaryId", Zend_Controller_Front::getInstance()->getRequest()->getParam("subsidiaryId"), null, $items);
                ?>
            </p>
            <p>
            <?php 
            echo $this->formLabel("encoding", "Kódování souboru:");
            echo $this->formSelect("encoding", null, array(), array("CP1250" => "CP-1250 (windows)", "UTF8" => "UTF-8"))
            ?>
            </p>
            <p>
                <?php echo $this->formSubmit("import-submit", "Importovat"); ?>
            </p>
        </form>
        <b>Pozor! při importu budou všechny stávající neshody, které nejsou vázány na audit smazány a nahrazeny novými!</b>
    </div>
</fieldset>
<?php 
}

$this->headScript()->appendFile("/js/audit/mistake/index.js");
?>
