<?php
$redirector = new Zend_Controller_Action_Helper_Redirector();

if ($this->isHtml) {
    $url = $this->url(array("clientId" => $this->clientId, "subsidiaryId" => $this->mistake["subsidiary_id"], "mistakeId" => $this->mistakeId), "audit-mistake-edit-html");
} else {
    $url = $this->url(array("clientId" => $this->clientId, "subsidiaryId" => $this->mistake["subsidiary_id"]), "audit-mistakes-index-subs");
}

$redirector->gotoUrlAndExit($url);