<script type="text/javascript">
<?php 
echo "var CLIENT_ID=" . $this->client->id_client . ";";
echo "var SUBSIDIARY_ID=" . $this->subsidiary->id_subsidiary . ";";
echo "var CHECK_ID=" . $this->check->id . ";";
?>
</script>
<h1>Prověrka</h1>
<h2><?php echo $this->client->company_name . " - " . $this->subsidiary->subsidiary_name; ?></h2>
<div id="tabs">
	<ul>
		<li><a href="#overview">Přehled</a></li>
		<li><a href="#mistakes">Neshody</a></li>
	</ul>
	<div id="overview">
		<table>
			<tbody>
				<tr>
					<td>
					Technik
					</td>
					<td>
						<strong><?php echo $this->userIndex[$this->check->checker_id]->username; ?></strong>
					</td>
				</tr>
				<tr>
					<td>
					Koordinátor
					</td>
					<td>
						<strong><?php echo $this->userIndex[$this->check->coordinator_id]->username; ?></strong>
					</td>
				</tr>
				<tr>
					<td>
					Zodpovědná osoba
					</td>
					<td>
						<strong><?php echo $this->check->responsibiles; ?></strong>
					</td>
				</tr>
				<tr>
					<td>
					Datum provedení
					</td>
					<td>
						<strong><?php echo $this->sqlDate($this->check->done_at); ?></strong>
					</td>
				</tr>
				<tr>
					<td>
					Technik potvrdil
					</td>
					<td>
						<strong><?php echo ($this->check->checker_confirmed_at == "0000-00-00 00:00:00") ? "Nepotvrdil" : $this->sqlDateTime($this->check->checker_confirmed_at); ?></strong>
					</td>
				</tr>
				<tr>
					<td>
					Koordinátor potvrdil
					</td>
					<td>
						<strong><?php echo ($this->check->coordinator_confirmed_at == "0000-00-00 00:00:00") ? "Nepotvrdil" : $this->sqlDateTime($this->check->coordinator_confirmed_at); ?></strong>
					</td>
				</tr>
				<tr>
					<td>
					Poznámka k průběhu
					</td>
					<td class="pre"><?php echo $this->check->progress_note; ?></td>
				</tr>
				<tr>
					<td>
					Shrnutí
					</td>
					<td class="pre"><?php echo $this->check->summary; ?></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="mistakes">
		<table id="mistake-list" class="multirow-table">
			<?php 
			echo $this->mistakeTable()->header(); 
			$actions = array("show" => "Zobrazit");
			
			foreach ($this->mistakes as $mistake) {
				// vyhodnoceni trid
				$classes = array();
				
				if ($mistake->is_removed) {
					$classes[] = "mistake-removed";
				} elseif ($mistake->is_marked) {
					$classes[] = "mistake-marked";
				}
				
				echo $this->mistakeTable()->mistake($mistake, $actions, $classes);
			}
			?>
		</table>
	</div>
</div>
<script type="text/javascript" src="/js/audit/check/get.js"></script>