<script type="text/javascript">
<?php 
echo "var CLIENT_ID=" . $this->client->id_client . ";";
echo "var SUBSIDIARY_ID=" . $this->subsidiary->id_subsidiary . ";";
echo "var CHECK_ID=" . $this->check->id . ";";
?>
</script>
<h1>Prověrka</h1>
<h2><?php echo $this->client->company_name . " - " . $this->subsidiary->subsidiary_name; ?></h2>
<div id="tabs">
	<ul>
		<li><a href="#overview">Přehled</a></li>
		<li><a href="#mistakes">Neshody</a></li>
	</ul>
	<div id="overview">
<?php
echo $this->editForm;
?>
	<em>*) Shrnutí je povinné vyplnit pouze před uzavřením auditu</em>
	<?php 
	if ($this->formSubmit) {
		echo "<h2>Uzavřít prověrku</h2>";
		echo $this->formSubmit;
	}
	?>
	</div>
	<div id="mistakes">
		<table id="mistake-table">
			<?php 
			echo $this->mistakeTable()->header();
			
			$this->mistakeTable()->workIndex = $this->workplaceIndex;
			
			foreach ($this->mistakes as $mistake) {
				$actions = array("edit-mistake" => "Upravit");
				
				if ($this->assocIndex[$mistake->id]->submit_status) {
					$actions["unsubmit-mistake"] = "Nepotvrzovat";
				} else {
					$actions["submit-mistake"] = "Potvrdit";
				}
				
				echo $this->mistakeTable()->mistake($mistake, $actions);
			}
			?>
		</table>
	</div>
</div>
<script type="text/javascript" src="/js/audit/check/edit.js"></script>
