<table>
	<tr>
		<td width="30%" align="left">
			<?php 
			$auditId = $this->audit->id;
			$clientId = $this->audit->client_id;
			$subsidiaryId = $this->audit->subsidiary_id;
			
			if ($this->pagination->prev) {
				$caption = "Předchozí";
				$href = "/audit/workplace/setplace?clientId=$clientId&auditId=$auditId&workplaceId=" . $this->pagination->prev;
				
				echo "<a href='$href'>$caption</a>";
			}
			?>
		</td>
		<td>
			<center>
			<?php echo $this->formSelect("paginator-workplace", $this->workplace->id_workplace, array(), $this->pagination->select); ?>
			</center>
		</td>
		<td width="30%" align="right">
			<?php 
			if ($this->pagination->next) {
				$caption = "Další";
				$href = "/audit/workplace/setplace?clientId=$clientId&auditId=$auditId&workplaceId=" . $this->pagination->next;
				
				echo "<a href='$href'>$caption</a>";
			}
			?>
		</td>
	</tr>
</table>
<?php
echo $this->commentForm;
?>
<form method="post" action="<?php echo $this->url(array("clientId" => $this->workplace->client_id, "auditId" => $this->audit->id), "audit-mistake-createalone2"); ?>">
	<p>
	<?php 
	echo $this->formHidden("workplace_id", $this->workplace->id_workplace);
	echo $this->formSubmit("submit", "Přidat neshodu");
	?>
	</p>
</form>
<table class="multirow-table" id="workplace-mistakes">
	<?php 
	echo $this->mistakeTable()->header(); 
	$config = array("actions" => array());
	foreach ($this->mistakes as $mistake) {
		// vyhodnoceni semaforu
		switch ($mistake->status) {
			case 1:
				$config["classes"] = array("mistake-marked");
				break;
				
			case 2:
				$config["classes"] = array("mistake-removed");
				break;
		}
		
		$config["actions"] = ($mistake->audit_id == $this->audit->id) ? array("edit" => "Upravit") : array("show" => "Zobrazit");
		echo $this->mistakeTable()->mistake($mistake, $config);
	}
	?>
</table>