<?php echo $this->form; ?>

<div class="hidden">
	<div id="new_workplace_form">
	<?php echo $this->formWorkplace; ?>
	</div>
</div>

<div class="hidden">
	<div id="new_work_form">
	<?php echo $this->formWork; ?>
	</div>
</div>

<div class="hidden">
	<div id="new_technicaldevice_form">
	<?php echo $this->formTechnicalDevice;?>
	</div>
</div>

<div class="hidden">
	<div id="new_chemical_form">
	<?php echo $this->formChemical;?>
	</div>
</div>

<div class="hidden">
	<div id="new_folder_form">
	<?php echo $this->formFolder;?>
	</div>
</div>

<div class="hidden">
	<div id="new_schooling_form">
	<?php echo $this->formSchooling;?>
	</div>
</div>

<div class="hidden">
	<div id="new_employee_form">
	<?php echo $this->formEmployee; ?>
	</div>
</div>