<?php echo $this->selectForm;?>
<?php if ($this->subsidiaryId != null){?>

	<div class="box">
	<?php if ($this->canCreatePosition){?>
		<a class="large" href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId), 'positionNew'); ?>">Přidat pracovní pozici</a>
		| <?php }
		if($this->filter == 'vse'){?>
		<a class="large" href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'neuplne'), 'positionList'); ?>">Vyfiltrovat neúplné pracovní pozice</a>
		<?php }else{?>
		<a class="large" href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'vse'), 'positionList'); ?>">Zobrazit všechny pracovní pozice</a>
		<?php }?>
	</div>
	
	<?php if($this->positions != null){ ?>
		<div class="box">
		<?php foreach($this->positions as $position){?>
		<div>
			&bull; <a class="show-info position-title"><?php echo $position['position']->getPosition();?></a>
			<?php if ($this->canEditPosition){ ?>
			| <a href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'positionId' => $position['position']->getIdPosition()), 'positionEdit');?>">Editovat</a>
			<?php }
			if ($this->canDeletePosition){?>
			| <form class="inline" action="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'positionId' => $position['position']->getIdPosition()), 'positionDelete')?>" method="post"><input class="button-anchor" type="submit" value="Smazat" onclick="return confirm('Opravdu si přejete smazat tuto pracovní pozici?')" /></form>
			<?php }?>
		</div>
		<div class="position-info hidden">
			<?php if($position['position']->getWorkingHours()){?>
				<p class="no-margin"><span class="bold">Pracovní doba: </span> <?php echo $position['position']->getWorkingHours()?></p>
			<?php }?>
			<?php if($position['position']->getNote()){?>
				<p class="no-margin"><span class="bold">Poznámka: </span> <?php echo $position['position']->getNote()?></p>
			<?php }?>
			<?php if($this->canViewPrivate){ 
				if($position['position']->getPrivate()){?>
				<p class="no-margin"><span class="bold">Soukromá poznámka: </span> <?php echo $position['position']->getPrivate()?></p>
			<?php }}?>
			<p class="no-margin">Kategorizace prací <span class="bold">
			<?php if($position['position']->getCategorization()){?>				
					byla 
				<?php } else {?>
					nebyla 
				<?php }?>
			</span>provedena</p>
			<?php if($position['position']->getCategorization() && isset($position['environmentFactors'])){?>
				<p class="no-margin"><span class="bold">Faktory pracovního prostředí:</span></p>
				<ul class="no-margin-bottom">
				<?php foreach($position['environmentFactors'] as $environmentFactor){?>
					<li><?php echo $environmentFactor['factor'];?></li>
					<li class="no-bullet"><span class="bold">Kategorie: </span><?php echo $environmentFactor['category'];?></li>
					<?php if($environmentFactor['source']){?>
						<li class="no-bullet"><span class="bold">Zdroj (popis): </span><?php echo $environmentFactor['source'];?></li>
					<?php }?>
					<?php if($environmentFactor['protection_measures']){?>
						<li class="no-bullet"><span class="bold">Ochranná opatření proti FPP: </span><?php echo $environmentFactor['protection_measures'];?></li>
					<?php }?>
					<?php if($environmentFactor['note']){?>
						<li class="no-bullet"><span class="bold">Poznámka: </span><?php echo $environmentFactor['note'];?></li>
					<?php }?>
					<?php if($this->canViewPrivate && $environmentFactor['private']){?>
						<li class="no-bullet"><span class="bold">Soukromá poznámka: </span><?php echo $environmentFactor['private'];?></li>
					<?php }?>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($position['schoolings'])){ ?>
				<p class="no-margin"><span class="bold">Školení pro pracovní pozici:</span></p>
				<ul class="no-margin-bottom">
				<?php foreach($position['schoolings'] as $schooling){?>
					<li><?php echo $schooling['schooling']?></li>
					<?php if($schooling['note']){?>
						<li class="no-bullet"><span class="bold">Poznámka: </span> <?php echo $schooling['note'];?></li>
					<?php }?>
					<?php if($this->canVievPrivate && $schooling['private']){?>
						<li class="no-bullet"><span class="bold">Soukromá poznámka: </span><?php echo $schooling['private'];?></li>
					<?php }?>
				<?php }?>
				</ul>
			<?php } ?>
			<?php if(isset($position['works'])){?>
				<p class="no-margin"><span class="bold">Pracovní činnosti (prováděné práce):</span></p>
				<ul class="no-margin-bottom">
				<?php foreach($position['works'] as $work){?>
					<li><?php echo $work['work']?></li>
					<?php if($work['frequency']){?>
						<li class="no-bullet"><span class="bold">Četnost pracovní činnosti: </span><?php echo $work['frequency'];?></li>
					<?php }?>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($position['technicalDevices'])){?>
				<p class="no-margin"><span class="bold">Technické prostředky:</span></p>
				<ul class="no-margin-bottom">
				<?php foreach($position['technicalDevices'] as $technicalDevice){?>
					<li><?php if ($technicalDevice['sort']){
						echo $technicalDevice['sort'];
					}?>
					<?php if ($technicalDevice['sort'] && $technicalDevice['type']){
						echo ' ';
					}?>
					<?php if ($technicalDevice['type']){
						echo $technicalDevice['type'];
					}?></li>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($position['chemicals'])){?>
				<p class="no-margin"><span class="bold">Chemické látky:</span></p>
				<ul class="no-margin-bottom">
				<?php foreach($position['chemicals'] as $chemical){?>
					<li><?php echo $chemical['chemical']?></li>
					<?php if($chemical['exposition']){?>
						<li class="no-bullet"><span class="bold">Expozice: </span><?php echo $chemical['exposition'];?></li>
					<?php }?>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($position['employees'])){?>
				<p class="no-margin"><span class="bold">Seznam zaměstanaců:</span></p>
				<ul class="no-margin-bottom">
				<?php foreach($position['employees'] as $employee){?>
					<li><?php echo $employee['first_name'] . ' ' . $employee['surname'];?></li>
				<?php }?>
				</ul>
			<?php }?>
			</div>
		<?php }?>
		</div>
	<?php } else {
		if($this->filter == "vse"){?>
		<p>Pobočka nemá žádné pracovní pozice.</p>
		<?php } else {?>
		<p>Pobočka nemá žádné neúplné pracovní pozice.</p>
		<?php }
	}?>
<?php }?>