<?php
$this->layout()->disableLayout();

// prirpava dokumentu
$xml = new SimpleXMLElement("<clients/>");

foreach ($this->clients as $client) {
	$clientNode = $xml->addChild("client");
	$clientNode->addAttribute("name", $client["company_name"]);
	$clientNode->addAttribute("id", $client["id_client"]);
	
	// pridani pobocek
	$subContainer = $clientNode->addChild("subsidiaries");
	
	foreach ($this->subsidiaries[$client["id_client"]] as $sub) {
		$name = $sub["subsidiary_name"] . " (" . $sub["subsidiary_town"] . " - " . $sub["subsidiary_street"] .  ")";
		$id = $sub["id_subsidiary"];
		
		$subElement = $subContainer->addChild("subsidiary");
		$subElement->addAttribute("name", $name);
		$subElement->addAttribute("id", $id);
	}
}

echo $xml->asXML()
?>