<?php
echo "<div>";

echo "<h2>Úprava pozice</h2>";

// formular
echo $this->form;

echo "<h2>Smazat</h2>";
echo "<form action='/document/documentation/delete' onsubmit='return confirm(\"Skutečně smazat?\")'>";
echo $this->formHidden("documentationId", $this->documentation->id);
echo $this->formHidden("clientId", $this->documentation->client_id);
echo $this->formSubmit("delete-submit", "Smazat");
echo "</form>";

// adresarova struktura pro vyber souboru
echo "<h2>Výběr souboru</h2>";
echo $this->formHidden("root-id", $this->root->id);

$attachUrl = $this->url(array("documentationId" => $this->documentation->id, "clientId" => $this->documentation->client_id), "document-documentation-attach");
?>
<div id="attach-path"></div>
<div>
	<form action="<?php echo $attachUrl; ?>" method="post" id="attach-file">
		Vybraný soubor: <strong id="attach-selected">-</strong>
		<input type="hidden" name="fileId" value="0" id="fileId1" />
		<input type="hidden" name="directoryId" value="0" id="directoryId1" />
		<button name="submit-client">Připojit jako veřejný</button>
		<button name="submit-internal">Připojit jako interní</button>
	</form>
</div>
<ul id="attach-content" style="list-style: none;"></ul>