<script type="text/javascript">
var CLIENT_ID = <?php echo $this->client->id_client; ?>;
</script>
<?php
$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();

// vyhodnoceni, jestli uzivatel muze dokumentaci upravovat
$editable = $acl->isAllowed($user->role, "document:documentation", "put");

echo "<h1>" . $this->client->company_name;
$subsidiaryId = null;

if ($this->subsidiary) {
	echo " - " . $this->subsidiary->subsidiary_name;
	$subsidiaryId = $this->subsidiary->id_subsidiary;
}

echo "</h1>";
?>
<h2>Dokumentace</h2>
<?php 
if ($editable) {
?>
<div class="box">
	<form action="<?php echo $this->url(array("clientId" => $this->client->id_client), "document-documentation-index"); ?>" method="get">
		<?php 
		$mo = $this->addForm->getElement("subsidiary_id")->getMultiOptions();
		$subList = array("-1" => "-- VŠECHNA DOKUMENTACE --");
		
		foreach ($mo as $k => $v) $subList[$k] = $v;
		
		echo $this->formSelect("subId", $this->subsidiaryId, array(), $subList);
		echo $this->formSubmit("filter-submit", "Filtrovat");
		?>
	</form>
	
<?php 
if ($acl->isAllowed($user->role, "document:preset")) {
	echo "<a href='/document/preset/index'>Přednastavená dokumentace</a>";
}
?>
</div>
<?php 
}
?>
<table id="docs-table">
	<thead>
		<tr>
			<td>
			Název
			</td>
			<td>
			Pobočka
			</td>
			<td>
			Komentář
			</td>
			<td>
			Soubor
			</td>
			<?php 
			if ($editable) {
				echo "<td>Interní</td>";
				echo "<td>Akce</td>";
			}
			?>
		</tr>
	</thead>
	<tbody>
	<?php 

foreach ($this->documentations as $doc) {
	// vyhodnoceni, zda se jedna o prazdny
	$class = ""; // $doc->fileid ? "" : "error";
	
	echo "<tr class='$class'>";
	
	echo "<td>$doc->name</td>";
	echo "<td>" . ($doc->subsidiary_name ? $doc->subsidiary_name : "CENTRÁLNÍ DOKUMENTACE") . "</td>";
	echo "<td>" . $doc->comment . "</td>";
	
	if ($editable) {
		echo "<td>" . ($doc->fileid ? $this->file((object) array("name" => $doc->filename, "id" => $doc->fileid), "show", $subsidiaryId) : "-") . "</td>";
		echo "<td>" . ($doc->i_fileid ? $this->file((object) array("name" => $doc->i_filename, "id" => $doc->i_fileid), "show", $subsidiaryId) : "-") . "</td>";
		echo "<td>" . ($editable ? $this->formButton("edit-" . $doc->id, "Upravit") : "&nbsp") . "</td>";
		
	} else {
		echo "<td>" . ($doc->fileid ? $this->file((object) array("name" => $doc->filename, "id" => $doc->fileid), "download") : "-") . "</td>";
	}
	
	echo "</tr>";
}
	?>
	</tbody>
</table>
<?php 
// pokud je uzivatel opravnen, zobrazi se formular na pridani
if ($acl->isAllowed($user->role, "document:documentation", "post")) {
	echo "<h3>Přidat novou dokumentaci</h3>";
	echo $this->addForm; 
}

if ($acl->isAllowed($user->role, "document:documentation", "reset")) {
	?>
<h2>Nastavit výchozí dokumentace</h2>
<form action="/document/documentation/reset?clientId=<?php echo $this->client->id_client; ?>" method="post" onsubmit="return confirm('Skutečně pokračovat?')">
	<em>Pozor! Při resetu bude stávající dokumentace smazána a nahrazena prázdnými sloty!</em>
	<table>
		<tr>
			<td>
			<?php echo $this->formLabel("subId", "Pobočka k resetu"); ?>
			</td>
			<td>
			<?php echo $this->formSelect("subId", null, array(), $subList); ?>
			</td>
		</tr>
		<tr>
			<td colspan="2">
			<?php echo $this->formSubmit("reset-submit", "Zresetovat"); ?>
			</td>
		</tr>
	</table>
</form>
	<?php 
}

// vypsani importu ze souboru, pokud ma uzivatel opravneni
if ($acl->isAllowed($user->role, "document:documentation", "import")) {
	?>
<h2>Import dokumentace ze souboru</h2>
<em>Funkce pro import souborů s definicí dokumentace vytvořených pomocí programu ClientReaper</em>
	<?php 
}
?>
<script type="text/javascript" src="/js/document/document.js"></script>