<link type="text/css" rel="stylesheet" href="/css/questionary.css">
<h1>Editace formuláře - <?php echo $this->form->name; ?></h1>
<a href="/audit/form/index">Zpět na seznam</a>
<?php
echo $this->editForm;

// smazani formulare
echo "<h2>Smazat formulář</h2>";
echo $this->formDelete;

// vypis kategorii tak, jak jdou posobe a vytvoreni formulare pro ulozeni noveho razeni
?>
<h2>Pořadí kategorií</h2>
<form action="/audit/form/sort" method="post">
	<ol id="catlist">
<?php 
foreach ($this->categories as $category) {
	$url = "/audit/section/edit?categoryId=" . $category->id . "&formId=" . $category->form_id;
	
	echo "<li><a href='$url'>" . $category->name . "</a>" . $this->formHidden("category[sort][]", $category->id) . "</li>";
}
?>
	</ol>
	<?php 
	echo $this->formHidden("formId", $this->form->id);
	echo $this->formSubmit("category[submit]", "Uložit");
	?>
</form>
<h2>Nová kategorie</h2>
<?php echo $this->categoryForm; ?>
<script type="text/javascript" src="/js/audit/form/edit.js"></script>