<h2>Založení auditu</h2>
<?php
echo $this->form;
?>
<?php 
if ($this->cloneForm) {
	?>
<h2>Klonovat starý audit</h2>
<p>
Je možné klonovat audit ze dne <?php echo $this->sqlDate($this->oldAudit->done_at); ?>
</p>
	<?php
	echo $this->cloneForm; 
}
?>
<script type="text/javascript">
$("#audit-done_at").datepicker({
	"dateFormat" : "dd. mm. yy",
	"dayNamesMin" : ["Ne", "Po", "Út", "St", "Čt", "Pá", "So"],
	"monthNames" : ["Leden", "Únor", "Březen", "Duben", "Květen", "Červen", "Červenec", "Srpen", "Září", "Říjen", "Listopad", "Prosinec"],
	"firstDay" : 1
});
</script>