<h2>Založení auditu</h2>
<?php
echo $this->form;
?>
<em>*) Pokud je potřeba zadat více osob, oddělujte čárkou</em>
<script type="text/javascript">
$("#audit-done_at").datepicker({
	"dateFormat" : "dd. mm. yy",
	"dayNamesMin" : ["Po", "Út", "St", "Čt", "Pá", "So", "Ne"],
	"monthNames" : ["Leden", "Únor", "Březen", "Duben", "Květen", "Červen", "Červenec", "Srpen", "Září", "Říjen", "Listopad", "Prosinec"]
});
</script>