<?php 
echo $this->formHidden("auditId", $this->audit->id);
echo $this->formHidden("clientId", $this->client->id_client);
echo $this->formHidden("client_id", $this->client->id_client);

printf("<h2>%s</h2>", $this->audit->is_check ? "Prověrka" : "Audit");
?>
<div id="tabs">
	<ul>
		<li><a href="#overview">Přehled</a></li>
		<li><a href="#forms"><?php echo $this->audit->is_check ? "Osnovy" : "Formuláře"; ?></a></li>
		<li><a href="#mistakes">Neshody</a></li>
		<li><a href="#deadlines">Lhůty</a></li>
		<li><a href="#workcomments">Kontrola pracovišť</a></li>
		<li><a href="#newworkplace">Nové pracoviště</a></li>
	</ul>
	<div id="overview" class="tab">
		<?php
		echo $this->form;
		
		// vyhodnoceni zobrazeni uzavreni auditu
		$audit = $this->audit;
		$userId = $this->userId;
		
		// vyhodnoceni, jestli je zprava vygenerovana
		if ($audit->report_id) {
			// tady bude odkaz na editaci zpravy
			echo "<fieldset><legend>Závěrečná zpráva</legend>";
			
			$url = $this->url(array("clientId" => $audit->client_id, "auditId" => $audit->id), "audit-report-edit");
			echo "<a href='$url'>Výstupní zpráva z auditu</a>";
			
			echo "</fieldset>";
		} else {
			// odkaz na vytvoreni zpravy
			$url = $this->url(array("clientId" => $audit->client_id, "auditId" => $audit->id), "audit-report-create");
			
			echo "<p><big><strong>Zpráva ještě není vytvořena</strong> <a href='$url'>Vytvořit zprávu</a></big></p>";
		}
		
		$isReport = $userId == $audit->auditor_id && $audit->report_id;
		
		echo "<div id='other-contact-person'>";
		echo "<h2>Jiná kontaktní osoba</h2>";
		echo $this->contactForm;
		echo "</div>";
		
		if ($isReport) {
			?>
		<h3>Uzavření auditu</h3>
			<?php 
			echo $this->submitForm;
		}
		?>
	</div>
	<div id="forms" class="tab">
		<table>
			<thead>
				<tr>
					<th>
					<?php echo $this->audit->is_check ? "Osnova" : "Formulář"; ?>
					</th>
				</tr>
			</thead>
			<tbody>
		<?php 
		if ($this->audit->is_check) {
			$route = "audit-farplan-edit";
			$paramName = "farplanId";
		} else {
			$route = "audit-form-fill";
			$paramName = "formId";
		}
		
		$params = array(
				"clientId" => $this->client->id_client,
				"subsidiaryId" => $this->subsidiary->id_subsidiary,
				"auditId" => $this->audit->id,
				"action" => "edit"
		);
		
		foreach ($this->formInstances as $instance) {
			$params[$paramName] = $instance->id;
			
			$href = $this->url($params, $route);
			
			?>
				<tr>
					<td>
					<a href="<?php echo $href; ?>"><?php echo $instance->name; ?></a>
					</td>
				</tr>
			<?php 
		}
		?>
			</tbody>
		</table>
		<?php echo $this->instanceForm; ?>
	</div>
	<div id="mistakes" class="tab">
		<h3>Nová neshoda</h3>
		<?php 
			printf("<form action='%s' method='post'>", $this->url(array("clientId" => $this->audit->client_id, "auditId" => $this->audit->id), "audit-mistake-createalone2"));
			echo $this->formHidden("mistake[workplace_id]", 0);
			echo $this->formSubmit("submit", "Vytvořit novou samostatnou neshodu");
			echo "</form>";
		?>
		<h3>Neshody zahrnuté v <?php echo $this->audit->is_check ? "prověrce" : "auditu"; ?></h3>
		<form action="<?php echo $this->url(array("auditId" => $this->audit->id, "clientId" => $this->audit->client_id), "audit-mistake-detach"); ?>" method="post">
		<table id="table-mistakes" class="multirow-table">
			<?php 
			$this->mistakeTable()->workIndex = $this->workIndex;
			
			echo $this->mistakeTable()->header();
			
			foreach ($this->auditMistakes as $mistake) {
				// vyhodnoceni semaforu
				$selector = $mistake->audit_id != $this->audit->id;
				$assoc = $this->mistakeAssocIndex[$mistake->id];
				
				$classes = array();
				
				// vyhodnoceni barvy
				if ($assoc->status == 2) {
					$classes = array("mistake-removed");
				} elseif ($mistake->is_marked) {
					$classes = array("mistake-marked");
				}
				
				// nastaveni tlacitek editovat a zobrazit
				$actions = array("edit-mistake" => "Upravit", "get-mistake" => "Zobrazit");
				
				echo $this->mistakeTable()->mistake($mistake, array("classes" => $classes, "actions" => $actions, "selector" => $selector));
			}
			?>
		</table>
		<p>
			<?php 
			echo $this->formSubmit("submit-solve", "Označit jako odstraněné");
			echo $this->formSubmit("submit-unsolve", "Označit jako NEodstraněné");
			?>
		</p>
		</form>
	</div>
	<div id="deadlines">
	<?php 
    printf("<p>%s</p>", $this->formButton("new-deadline", "Přidat novou lhůtu"));
    
	$options = array(
			"buttons" => array(
					"show" => array(
							"caption" => "Zobrazit",
							"type" => "button"
							),
					"edit" => array(
							"type" => "button",
							"caption" => "Editovat"
							),
					"selected[]" => array(
							"type" => "checkbox",
							"caption" => "Vybrat"
							)
					)
			);
	
	$options["form"] = array("action" => "/audit/audit/subdead?auditId=" . $audit->id);
	
	echo $this->deadlineTable($this->deadlines, $options);
	echo $this->formButton("add-deadlines", "Zkontrolovat ostatní lhůty");
    
    $this->headScript()->appendFile("/js/deadline/deadline.js");
	?>
	</div>
	<div id="newworkplace">
		<div id="new-workplace-form">
			<?php echo $this->placeForm; ?>
		</div>
	</div>
	<div id="workcomments">
		<?php echo $this->action("get", "workplace", "audit", array("auditId" => $this->audit)); ?>
	</div>
</div>

<div class="multiCheckboxWorkplaces"></div>

<div class="hidden" id="new_position_form">
	<?php echo $this->postForm; ?>
</div>
<div class="hidden" id="new_work_form">
	<?php echo $this->workForm; ?>
</div>
<div class="hidden" id="new_chemical_form">
	<?php echo $this->chemForm; ?>
</div>
<div class="hidden" id="new_technicaldevice_form">
	<?php echo $this->techForm; ?>
</div>
<div class="hidden" id="new_folder_form">
	<?php echo $this->folderForm; ?>
</div>
<div class="hidden" id="new_boss_form">
    <?php echo $this->bossForm; ?>
</div>
<?php
$this->headScript()->appendFile("/js/audit/audit/edit.js");
?>