<h1>Audit</h1>
<h2><?php echo $this->client->company_name . " - " . $this->subsidiary->subsidiary_name; ?></h2>
<div id="questionary"></div>
<script type="text/javascript">
var QDATA = <?php echo Zend_Json::encode($this->questionary->toArray()); ?>
</script>
<?php
echo $this->form;
?>
<script type="text/javascript" src="/js/questionary.items.js"></script>
<script type="text/javascript" src="/js/audit/audit/fill.js"></script>