<script type="text/javascript">
<?php 
echo "var CLIENT_ID=" . $this->client->id_client . ";";
echo "var SUBSIDIARY_ID=" . $this->subsidiary->id_subsidiary . ";";
echo "var AUDIT_ID=" . $this->audit->id;

$today = (int) Zend_Date::now()->get("yMMdd");
?>
</script>
<?php printf("<h2>%s</h2>", $this->audit->is_check ? "Prověrka" : "Audit"); ?>
<div id="tabs">
	<ul>
		<li><a href="#overview">Přehled auditu</a></li>
		<li><a href="#forms">Formuláře</a></li>
		<li><a href="#mistakes">Neshody</a>
		<li><a href="#deadlines">Lhůty</a></li>
	</ul>
	<div id="overview">
	<?php 
	echo $this->partial("audit/_commonTable.phtml", $this);
	
	if ($this->audit->report_id)
		printf("<div><a href='%s'>Výstupní zpráva</a></div>", $this->url(array("auditId" => $this->audit->id, "subsidiaryId" => $this->audit->subsidiary_id, "clientId" => $this->audit->client_id), "audit-report-get"));
	?>
	</div>
	<div id="forms">
		<table>
			<thead>
				<tr>
					<th>Formulář</th>
					<th>
					&nbsp;
					</th>
				</tr>
			</thead>
			<tbody>
			<?php 
			$route = "audit-form-get";
			$paramName = "formId";
			
			
			// sestaveni parametru
			$params = array(
					"clientId" => $this->audit->client_id,
					"subsidiaryId" => $this->audit->subsidiary_id,
					"auditId" => $this->audit->id
			);
			
			foreach ($this->forms as $form) {
				$params[$paramName] = $form->id;
				?>
				<tr>
					<td>
					<?php echo $form->name; ?>
					</td>
					<td>
					<?php 
					$url = $this->url($params, $route);
					
					echo "<a href='$url'>Zobrazit</a>";
					?>
					</td>
				</tr>
				<?php 
			}
			?>
			</tbody>
		</table>
	</div>
	<div id="mistakes">
		<div class="box">
			<?php 
			echo $this->formLabel("display-mistakes", "Zobrazit : ");
			echo $this->formSelect("display-mistakes", null, null, array("ALL" => "---Vše--", "FORM" => "Neshody z formulářů", "OTHER" => "Ostatní neshody"));
			?>
		</div>
		<div id="mistakes-forms">
			<h3>Neshody z formulářů</h3>
			<table id="tab-forms" class="multirow-table">
				<?php 
				echo $this->mistakeTable()->header();
				$actions = array("show-mistake" => "Podrobnosti");
				$workplaceMistakes = array();
				
				foreach ($this->mistakes as $mistake) {
					// vyhodnoceni trid
					if ($mistake->workplace_id) {
						$workplaceMistakes[] = $mistake;
						continue;
					}
					$classes = array();
					
					if ($mistake->is_removed) {
						$classes[] = "mistake-removed";
					} elseif ($mistake->isMarked($today)) {
						$classes[] = "mistake-marked";
					}
					
					echo $this->mistakeTable()->mistake($mistake, array("actions" => $actions, "classes" => $classes, "subsidiaryRow" => false));
				}
				?>
			</table>
		</div>
		<div id="mistakes-others">
			<h3>Neshody z pracovišť</h3>
			<table id="tab-others" class="multirow-table">
				<?php 
				echo $this->mistakeTable()->header();
				
				$this->mistakeTable()->workIndex = $this->workplaceIndex;
				
				foreach ($workplaceMistakes as $mistake) {
					// vyhodnoceni trid
					$classes = array();
					
					if ($mistake->is_removed) {
						$classes[] = "mistake-removed";
					} elseif ($mistake->isMarked($today)) {
						$classes[] = "mistake-marked";
					}
					
					echo $this->mistakeTable()->mistake($mistake, array("actions" => $actions, "classes" => $classes, "subsidiaryRow" => false));
				}
				?>
			</table>
		</div>
	</div>
	<div id="deadlines">
	<?php 
	$options = array(
			"buttons" => array(
					"show" => array(
							"caption" => "Zobrazit",
							"type" => "button"
					)
			),
        "subsidiaryRow" => false
	);
	
	echo $this->deadlineTable($this->deadlines, $options); 
	?>
	</div>
</div>
<script type="text/javascript" src="/js/audit/audit/get.js"></script>