<h1>Audity a prověrky</h1>
<h2><?php echo $this->client->company_name; ?></h2>
<em>PT - potvrzeno technikem; PK - potvrzeno koordinátorem</em>
<table>
	<thead>
		<tr>
			<th>
			Pobočka
			</th>
			<th>
			Datum provedení
			</th>
			<th>
			Typ
			</th>
			<th>
			PT
			</th>
			<th>
			PK
			</th>
			<th>
			Akce
			</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$subIndex = $this->subIndex;
	$user = Zend_Auth::getInstance()->getIdentity();
	
	foreach ($this->audits as $audit) {
		// vyhodnoceni akce
		$route = "audit-get";
		$caption = "Zobrazit";
		
		switch ($user->role) {
			case My_Role::ROLE_ADMIN:
				$route = "audit-edit";
				$caption = "Upravit";
				break;
				
			case My_Role::ROLE_TECHNICIAN:
				if ($audit->auditor_confirmed_at[0] == '0') {
					$route = "audit-edit";
					$caption = "Upravit";
				}
				break;
				
			case My_Role::ROLE_COORDINATOR:
				if ($audit->auditor_confirmed_at[0] != '0' && $audit->coordinator_confirmed_at[0] == '0') {
					$route = "audit-edit";
					$caption = "Upravit";
				}
				break;
		}
		
		$href = $this->url(array("clientId" => $audit->client_id, "auditId" => $audit->id, "subsidiaryId" => $audit->subsidiary_id), $route);
		$action = "<a href='$href'>$caption</a>";
		?>
		<tr>
			<td><?php echo $subIndex[$audit->subsidiary_id]->subsidiary_name; ?></td>
			<td><?php echo $this->sqlDate($audit->done_at); ?></td>
			<td><?php echo $audit->is_check ? "Prověrka" : "Audit"; ?></td>
			<td><?php echo $audit->auditor_confirmed_at[0] == '0' ? "Ne" : "Ano"; ?></td>
			<td><?php echo $audit->coordinator_confirmed_at[0] == '0' ? "Ne" : "Ano"; ?></td>
			<td><?php echo $action; ?></td>
		</tr>
		<?php 
	}
	?>
	</tbody>
</table>