<h1>Audity a prověrky</h1>
<div class="box">
	<a href='<?php 
	$request = Zend_Controller_Front::getInstance()->getRequest();
	echo $this->url(array("clientId" => $request->getParam("clientId"), "subsidiaryId" => $request->getParam("subsidiaryId")), "audit-create"); 
	?>'>Provést audit</a>
</div>
<em>PT - potvrzeno technikem</em>
<table>
	<thead>
		<tr>
			<th>
			Technik
			</th>
			<th>
			Datum provedení
			</th>
			<th>
			Typ
			</th>
			<th>
			PT
			</th>
			<th>
			Akce
			</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$subIndex = $this->subIndex;
	$user = Zend_Auth::getInstance()->getIdentity();
	
	foreach ($this->audits as $audit) {
		// vyhodnoceni akce
		$route = "audit-get";
		$caption = "Zobrazit";
		
		// vyhodnoceni moznosti editace
		if ($user->role == My_Role::ROLE_ADMIN || ($audit->auditor_id == $user->id_user && !$audit->is_closed)) {
			$route = "audit-edit";
			$caption = "Upravit";
		}
		
		$href = $this->url(array("clientId" => $audit->client_id, "auditId" => $audit->id, "subsidiaryId" => $audit->subsidiary_id), $route);
		$action = "<a href='$href'>$caption</a>";
		?>
		<tr>
			<td><?php echo $audit->auditor_name; ?></td>
			<td><?php echo $this->sqlDate($audit->done_at); ?></td>
			<td><?php echo $audit->is_check ? "Prověrka" : "Audit"; ?></td>
			<td><?php echo $audit->auditor_confirmed_at[0] == '0' ? "Ne" : "Ano"; ?></td>
			<td><?php echo $action; ?></td>
		</tr>
		<?php 
	}
	?>
	</tbody>
</table>