<?php
if (Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId")) $this->layout()->setLayout("client-layout");
?>
<h1>O GUARDIANU</h1>
<p>
GUARDIAN je informačním a komunikačním portálem bezpečnosti práce a požární ochrany.
</p>
<p>
Portál je určen pro klienty společnosti G U A R D 7, v.o.s.
</p>
<p>
Uživatel má k dispozici všechny podstatné informace týkající se BOZP a PO v jeho společnosti.
</p>
<p>
Naleznete zde přehledný registr neshod, dokumentaci BOZP a PO, lhůtníky, protokoly z dohlídek na pracovišti, výstupy z ročních prověrek a další důležité informace.
</p>
<p>
Pomocí GUARDIANU je možné komunikovat s koordinátory společnosti G U A R D 7, v.o.s. - zasílat své připomínky, náměty, žádosti, objednávky apod.
</p>
<p>
Upravovat informace obsažené v GUARDIANU mohou kromě koordinátorů a bezpečnostních techniků G UA R D 7, v.o.s. také samotní klienti. Veškeré provedené změny jsou zaznamenávány do bezpečnostního deníku, kde je možné dohledat kdy a kým byla změna provedena.
</p>