<?php
if (Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId")) $this->layout()->setLayout("client-layout");
?>
<table id="contact-table-tech">
    <tr>
        <td style="margin: 10px;">
            <strong>G U A R D 7, v.o.s.</strong><br />
            Divišova 235, 530 03 Pardubice<br />
            IČ: 48173622<br />
            DIČ: 48173622<br />
        </td>
        <td>
            <img src="/images/logo.gif" />
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <a href="http://www.mapy.cz/#q=Pardubice%2C%20Divi%C5%A1ova%20235&qp=15.766704_50.034332_15.772977_50.037573_16&z=16&x=15.813687&y=50.032007&u=u&t=s" target="_blank">Mapa sídla společnosti</a>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <strong>Telefon:</strong> +420 466 535 700<br />
            <strong>E-mail:</strong> <a href="mailto:guard7@guard7.cz">guard7@guard7.cz</a><br />
            <a href="http://www.guard7.cz" target="_blank">www.guard7.cz</a>
        </td>
    </tr>
    <tr>
        <td>
            <strong>JEDNATEL SPOLEČNOSTI</strong><br />
            Bc. Miloš Eichler <br />
            e-mail: <a href="mailto:eichler@guard7.cz">eichler@guard7.cz</a><br />
            mobil: +420 605 246 604
        </td>
        <td>
            <strong>EKONOMICKÝ ŘEDITEL</strong><br />
            Ing. Renata Eichlerová<br />
            e-mail: <a href="mailto:renata.eichlerova@guard7.cz">renata.eichlerova@guard7.cz</a><br />
            mobil: +420 605 246 605
        </td>
    </tr>
    <tr>
        <td>
            <strong>HLAVNÍ KOORDINÁTOR</strong><br />
            Ing. Anna Suková<br />
            e-mail: <a href="mailto:anna.sukova@guard7.cz">anna.sukova@guard7.cz</a><br />
            mobil: +420 603 464 712
        </td>
        <td>
            <strong>KOORDINÁTOR</strong><br />
            Martina Kočová<br />
            e-mail: <a href="mailto:martina.kocova@guard7.cz">martina.kocova@guard7.cz</a><br />
            mobil: +420 603 456 209
        </td>
    </tr>
    <tr>
        <td>
            <strong>PODPORA E-LEARNINGU</strong><br />
            Ing. Jan Tesař<br />
            e-mail: <a href="mailto:jan.tesar@guard7.cz">jan.tesar@guard7.cz</a><br />
            telefon: +420 734 834 070
        </td>
    </tr>
</table>
<?php
if (!Zend_Auth::getInstance()->getIdentity()) return;
?>
<h2>Bezpečnostní technici</h2>
<table id="contact-table-tech">
    <tr>
        <td>
            Bc. Jiří Hora<br />
            Email: <a href="mailto:hora@guard7.cz">hora@guard7.cz</a><br />
            Telefon: +420 604 208 145
        </td>
        <td>
            Ing. Jiří Kvapil<br />
            Email: <a href="mailto:kvapil@guard7.cz">kvapil@guard7.cz</a><br />
            Telefon: +420 605 246 667
        </td>
    </tr>
    <tr>
        <td>
            Ing. Jiří Kratochvíl<br />
            Email: <a href="mailto:kratochvil@guard7.cz">kratochvil@guard7.cz</a><br />
            Telefon: +420 605 246 607
        </td>
        <td>
            Ing. Jan Modráček<br />
            Email: <a href="mailto:modracek@guard7.cz">modracek@guard7.cz</a><br />
            Telefon: +420 605 246 608
        </td>
    </tr>
</table>