	<?php if ($this->subsidiaries){?>
	<div class="box">
		<h2>Pobočky</h2>
		<ul><?php foreach ($this->subsidiaries as $subsidiary){ 
			$item = $subsidiary["subsidiary"];
			
			if ($item->getHq()){
			?>
			<li><a href="<?php echo $this->url(array('clientId' => $item->getClientId()), 'clientIndex') ?>"><?php printf("%s, %s, %s (centrála)", $item->getSubsidiaryName(), $item->getSubsidiaryTown(), $item->getSubsidiaryStreet()); ?></a></li>
			<?php 
			} else {
			?>
			<li><a href="<?php echo $this->url(array('clientId' => $item->getClientId(), 'subsidiary' => $item->getIdSubsidiary()), 'subsidiaryIndex') ?>"><?php printf("%s, %s %s (centrála)", $item->getSubsidiaryName(), $item->getSubsidiaryTown(), $item->getSubsidiaryStreet()); ?></a></li>
		<?php }
		}?></ul>
	</div>
	<?php }
	$user = Zend_Auth::getInstance()->getIdentity();
	
	// nic z toho se klientum nebude zobrazovat
	if ($user->role == My_Role::ROLE_CLIENT) return;
	?>
	<div class="box tasks">
		<h2>Osobní úkoly</h2>
		<p>neshody nebo lhůty, u kterých je zadáno jméno - přiděluje KOO popřípadě KL, Při auditu se vyplní pouze G7 nebo KL.</p>
	</div>
	<div>
		<h2>Bezpečnostní deník</h2>
		<p>dodělat okno pro psaní zpráv a odesílání souborů</p>
		<?php echo $this->formFilter;?>
		<?php echo $this->formSearch;?>
		<div class="overflow"><?php echo $this->diary();?></div>
		<hr/>
		<h2>Poslat zprávu</h2>
		<p class="bold">Zde můžete zaslat zprávu do bezpečnostního deníku zvolených poboček:</p>
		<div id="zpravy"><?php echo $this->formMessages; ?></div>
	</div>
	<div class="box deadlines">
		<h2>Termíny a lhůty</h2>
		<p>NESHODY a LHŮTNÍKY nastavené je filtrování podle termínu. Celkový přehled o blížících se a propadlých termínech. Možnost hypertext se prokliknout na kartu KL, kterém neshoda nebo lhůta náleží.
		</p>
	</div>