<?php
// vypnuti layoutu
$this->layout()->disableLayout();

$document = new PHPExcel();

// ziskani sheetu
$document->setActiveSheetIndex(0);
$sheet = $document->getActiveSheet();

// zapis hlavicky
$sheet->setCellValue('A1', 'Pobočka');
$sheet->setCellValue('B1', 'Druh');
$sheet->setCellValue('C1', 'Specifikace');
$sheet->setCellValue('D1', 'Perioda');
$sheet->setCellValue('E1', 'Naposledy provedeno');
$sheet->setCellValue('F1', 'Další provedení');
$sheet->setCellValue('G1', 'Provádí');
$sheet->setCellValue('H1', 'Jméno / Název');
$sheet->setCellValue('I1', 'Poznámka');

foreach (range("A", "J") as $c) {
	$dim = $sheet->getColumnDimension($c);

	switch ($c) {
		default:
			$dim->setAutoSize(true);
	}
}

// zapis dat
$i = 2;

foreach($this->deadlines as $deadline) {
	// vyhodnoceni typu
	switch ($deadline->type) {
		case Deadline_Form_Deadline::TYPE_ELEARNING:
			$type = "Elearning";
			break;
				
		case Deadline_Form_Deadline::TYPE_PRESENT:
			$type = "Prezenční";
			break;
				
		default:
			$type = "Jiná";
	}

	// vyhodnoceni zodpovedne osoby
    if ($deadline->anonymous_employee) {
        $resp = "Neurčený zaměstnanec";
    } elseif ($deadline->anonymous_guard) {
        $resp = "GUARD7";
    } else {
        $resp = $deadline->responsible_name;
    }

	$sheet->setCellValue('A' . $i, sprintf("%s - %s. %s", $deadline->subsidiary_name, $deadline->subsidiary_town, $deadline->subsidiary_street));
	$sheet->setCellValue('B' . $i, $deadline->kind);
	$sheet->setCellValue('C' . $i, $deadline->specific);
	$sheet->setCellValue('D' . $i, $deadline->period);
	$sheet->setCellValue('E' . $i, $this->sqlDate($deadline->last_done));
	$sheet->setCellValue('F' . $i, $this->sqlDate($deadline->next_date));
	$sheet->setCellValue('G' . $i, $resp);
	$sheet->setCellValue('H' . $i, $deadline->name ? $deadline->name : "-");
	$sheet->setCellValue('I' . $i, $deadline->note);

	$i++;
}

// nastavei stylu
$cells = $sheet->getStyle('A1:I' . $i);
$cells->getAlignment()->setWrapText(true); 
$cells->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_MEDIUM);
$cells->getBorders()->getAllBorders()->setColor(new PHPExcel_Style_Color());

// nastaveni pozadi hlavicky
$sheet->getStyle("A1:I1")->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->setStartColor(new PHPExcel_Style_Color("FFBBBBBB"));
$sheet->getStyle('D2:D' . $i)->getAlignment()->setHorizontal("center");

// Redirect output to a client’s web browser (Excel5)
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="neshody.xls"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');

// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified

$objWriter = PHPExcel_IOFactory::createWriter($document, 'Excel2007');
$objWriter->save('php://output');
