<?php 
// navratovy odkaz
$request = Zend_Controller_Front::getInstance()->getRequest();

$params = array(
		"clientId" => $request->getParam("clientId"),
		"subsidiaryId" => $request->getParam("subsidiaryId")
		);

$url = $this->url($params, "deadline-index");

if (!$this->disableReturnLink)
    printf("<a href='%s'>Zpět na výběr kategorie lhůty</a>", $url);

$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();

$options = array("name" => $this->caption, "subsidiaryRow" => $this->subsidiaryRow, "nameFilter" => true);
$clientId = Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId", 0);

$options["buttons"] = array("get" => array("type" => "button", "caption" => "Zobrazit"));

if ($acl->isAllowed($user->role, "deadline:deadline", "put")) {
	$options["buttons"]["edit"] = array("type" => "button", "caption" => "Editovat");
    $options["form"] = array("action" => "/deadline/deadline/submits?clientId=" . $clientId);

    $options["buttons"]["selected[]"] = array("caption" => "Vybrat", "type" => "checkbox");
}

echo $this->formHidden("CLIENT_ID", $clientId);

$this->filterForm->setAction("#deadlines");

echo $this->showHidePanel($this->filterForm, "Filtrace", "Zobrazit/skrýt filtraci", true);

if (in_array($user->role, array(My_Role::ROLE_ADMIN, My_Role::ROLE_COORDINATOR))) {
    // vygenerovani tlacitka pro odkaz na XLS
    $params = $_SERVER["QUERY_STRING"];
    $xlsUrl = "/deadline/index/$this->xlsAction.xls?clientId=" . $request->getParam("clientId") . "&subsidiaryId=" . $request->getParam("subsidiaryId") . "&" . $params;

    printf("<p><form action='%s' target='_blank' method='post'><input type='submit' value='Stáhnout ve formátu MS Excel (beta)'></form></p>", $xlsUrl);
}

// nastaveni formulare - mozna pozdeji osetrit pravy

// nacteni ACL a vyhodnoceni akci
echo $this->deadlineTable($this->deadlines, $options);

$this->headScript()->appendFile("/js/deadline/deadline.js");
?>
