<?php
$params = array(
		"clientId" => Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId"),
		"subsidiaryId" => $this->subsidiary->id_subsidiary
		);
?>
<ul>
	<li>
		<a href="<?php echo $this->url($params, "deadline-employees")?>">Lhůty zaměstnanců</a>
	</li>
	<li>
		<a href="<?php echo $this->url($params, "deadline-devices")?>">Lhůty technických zařízení</a>
	</li>
	<li>
		<a href="<?php echo $this->url($params, "deadline-others")?>">Ostatní lhůty</a>
	</li>
</ul>
<?php 
echo "<h1>Všechny lhůty</h1>";
$acl = new My_Controller_Helper_Acl();
$user = Zend_auth::getInstance()->getIdentity();

if ($acl->isAllowed($user->role, "deadline:deadline", "post")) {
	$content = $this->action("create", "deadline", "deadline", Zend_Controller_Front::getInstance()->getRequest()->getParams());
    
    $form = new Deadline_Form_Deadline();
    $form->populate(Zend_Controller_Front::getInstance()->getRequest()->getParams());
    
    echo $this->showHidePanel($content, "Nová lhůta", "Zobrazit/skrýt formulář", is_null($form->getValue("subsidiary_id")));
}

echo $this->action("all", "index", "deadline", Zend_Controller_Front::getInstance()->getRequest()->getParams());

if ($acl->isAllowed($user->role, "deadline:deadline", "import")) {
	?>
<fieldset>
    <legend>Import lhůt</legend>
    <div>
        <?php echo $this->formButton("display-import-dead", "Zobrazit/skrýt import lhůt", array("onclick" => "$('#deadline-impdiv').toggle()")); ?>
    </div>
    <div id="deadline-impdiv" style="display: none; ">
        <?php echo $this->importForm; ?>
    </div>
</fieldset>
<?php
}

if ($acl->isAllowed($user->role, "deadline:deadline", "clear")) {
    ?>
<fieldset>
    <legend>Smazání lhůt</legend>
    <div>
        <?php echo $this->formButton("display-import-dead", "Zobrazit/skrýt vyčištení lhůt", array("onclick" => "$('#deadline-clear').toggle()")); ?>
    </div>
    <div id="deadline-clear" style="display: none; ">
        <form action="/deadline/deadline/clear" method="post" onsubmit="return confirm('Skutečně chcete vymazat lhůty? Tato akce nelze vrátit zpět!')">
            <div>
            <?php 
            echo $this->formSubmit("clear-submit", "Smazat lhůty");
            echo $this->formHidden("subsidiaryId", $this->subsidiary->id_subsidiary);
            ?></div>
        </form>
    </div>
</fieldset>
<?php
}
?>