<?php
$params = array(
		"clientId" => Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId"),
		"subsidiaryId" => $this->subsidiary->id_subsidiary
		);
?>
<ul>
	<li>
		<a href="<?php echo $this->url($params, "deadline-employees")?>">Lhůty zaměstnanců</a>
	</li>
	<li>
		<a href="<?php echo $this->url($params, "deadline-devices")?>">Lhůty technických zařízení</a>
	</li>
	<li>
		<a href="<?php echo $this->url($params, "deadline-others")?>">Ostatní lhůty</a>
	</li>
</ul>
<?php 
$acl = new My_Controller_Helper_Acl();
$user = Zend_auth::getInstance()->getIdentity();

if ($acl->isAllowed($user->role, "deadline:deadline", "post")) {
	$content = $this->action("create", "deadline", "deadline", Zend_Controller_Front::getInstance()->getRequest()->getParams());
    
    $form = new Deadline_Form_Deadline();
    $form->populate(Zend_Controller_Front::getInstance()->getRequest()->getParams());
    
    echo $this->showHidePanel($content, "Nová lhůta", "Zobrazit/skrýt formulář", is_null($form->getValue("subsidiary_id")));
}

echo $this->action("all", "index", "deadline", Zend_Controller_Front::getInstance()->getRequest()->getParams());

if ($acl->isAllowed($user->role, "deadline:deadline", "import")) {
	?>
<fieldset>
    <legend>Import lhůt</legend>
    <div>
        <?php echo $this->formButton("display-import-dead", "Zobrazit/skrát import lhůt", array("onclick" => "$('#deadline-impdiv').toggle()")); ?>
    </div>
    <div id="deadline-impdiv" style="display: none; ">
        <?php echo $this->importForm; ?>
    </div>
</fieldset>
<?php
}
?>