<?php
if ($this->REQ_TYPE == Document_DocumentationController::REQ_DOC) {
    ?>
<h1>Přednastavená dokumentace</h1>
<h2>Obecná dokumentace</h2>
    <?php
} else {
    ?>
<h1>Přednastavené záznamy</h1>
<h2>Obecné záznamy</h2>
<?php
}
    ?>
<table>
	<thead>
		<tr>
			<th>
			Jméno
			</th>
			<th>
			Akce
			</th>
		</tr>
	</thead>
	<tbody>
<?php 
foreach ($this->commons as $item) {
	?>
		<tr>
			<td>
			<?php echo $item->name; ?>
			</td>
			<td>
			<?php echo "<a href='/document/preset/delete?TYPE=$this->REQ_TYPE&presetId=$item->id' onclick='return confirm(\"Skutečně smazat?\")'>Smazat</a>"; ?>
			</td>
		</tr>
	<?php 
}
?>
	</tbody>
</table>
<h2><?php echo $this->REQ_TYPE == "DOC" ? "Dokumentace pro pobočku" : "Záznamy pro pobočku"; ?></h2>
<table>
	<thead>
		<tr>
			<th>
			Jméno
			</th>
			<th>
			Akce
			</th>
		</tr>
	</thead>
	<tbody>
<?php 
foreach ($this->noCommons as $item) {
	?>
		<tr>
			<td>
			<?php echo $item->name; ?>
			</td>
			<td>
			<?php echo "<a href='/document/preset/delete?TYPE=$this->REQ_TYPE&presetId=$item->id' onclick='return confirm(\"Skutečně smazat?\")'>Smazat</a>"; ?>
			</td>
		</tr>
	<?php 
}
?>
	</tbody>
</table>
<h2><?php echo $this->REQ_TYPE == "DOC" ? "Nová přednastavená dokumentace" : "Nové přednastavené záznamy"; ?></h2>
<?php
echo $this->form;