<?php 
$this->layout()->setLayout("floating-layout");

$deadline = $this->deadline;
$helper = $this->tableLayout();
?>
<h2>Přehled lhůty</h2>
<table>
	<tbody>
		<?php
		$params = array(
				"first" => array(
						"class" => "strong"
						)
				);
		
		// vyhodnoceni typu
		switch ($deadline->type) {
			case Deadline_Form_Deadline::TYPE_ELEARNING:
				$type = "E-learning";
				break;
				
			case Deadline_Form_Deadline::TYPE_PRESENT:
				$type = "Prezenční";
				break;
				
			default:
				$type = "Jiná";
		}
		
		echo $helper->row("Jméno / Zařízení", $deadline->name, $params);
		echo $helper->row("Druh", $deadline->kind, $params); 
		echo $helper->row("Specifikace", $deadline->specific, $params);
		echo $helper->row("Forma", $type, $params);
		echo $helper->row("Perioda (měsíců)", $deadline->period, $params);
		echo $helper->row("Naposledy provedeno", $deadline->last_done, $params);
		echo $helper->row("Další provedení", $deadline->next_date, $params);
		echo $helper->row("Poznámka", $deadline->note, $params);
		echo $helper->row("Zodpovědná osoba", $deadline->responsible_name, $params);
		?>
	</tbody>
</table>
<?php 
// zobrazeni historie
if ($this->logs->count()) {
	echo $this->partial("deadline/_logs.phtml", $this);
}

// pokud neni zodpovedna osoba G7, zobrazi se formular pro odeslani
$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();

if ($acl->isAllowed($user->role, "deadline:deadline", "submit")) {
	echo "<h2>Splnit lhůtu</h2>";
	echo $this->formSubmit;
}
?>
<script type="text/javascript" src="/js/deadline/deadline.js"></script>