<ul>
	<li><a href="#">Dohlídka</a>
		<ul><li><a href="#">Historie dohlídek (protokoly)</a></li></ul>
	</li>
	<li><a href="#">Audit</a></li>
	<li><a href="#">Výroční zpráva</a></li>
	<li><a href="#">Roční prověrka</a></li>
	<li><a href="#">Kniha kontrol</a></li>
	<li><a href="#">Kniha úrazů</a></li>
	<li><a href="#">Záznam o úrazu</a></li>
	<li><a href="<?php echo $this->url(array('clientId' => $this->clientId), 'printDiary');?>">Historie BD</a></li>
</ul>