<?php
// vyhodnoceni jestli je uzivatel opravnen vytvaret nove ukoly
$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();

/**
 * echo $this->formButton("all-tasks", "Zobrazit všechny úkoly", array("subid" => $this->subsidiaryId));
 * zakomentovano, protoze byla zadost k odstraneni - pozdeji az bude jiste ze to nikdo nebude chtit vratit zpet, tak se to smazne
 */

if ($acl->isAllowed($user->role, "task", "post")) {
	
	echo $this->formButton("create-task", "Nový úkol", array("subid" => $this->subsidiaryId));
}

$completable = $acl->isAllowed($user->role, "task", "complete");

if ($completable) {
	$format = sprintf("<form action='/task/complete'>%%s<div>%s</div></form>", $this->formSubmit("task-complete-submit", "Splnit označené úkoly"));
} else {
	$format = "%s";
}

$config = array("editable" => $acl->isAllowed($user->role, "task", "put"), "completable" => $completable);
?>
<form>
	<?php 
	$currFilter = Zend_Controller_Front::getInstance()->getRequest()->getParam("filter", 1);
	echo $this->formLabel("filter", "Zobrazovat: ");
	echo $this->formSelect("filter", $currFilter, null, array("Vše", "Aktuální", "Odstraněné"));
	echo $this->formSubmit("submit", "Filtrovat");
	echo $this->formHidden("subsidiaryId", $this->subsidiaryId);
	?>
</form>
<?php 
printf($format, $this->tasks($this->tasks, $config));