<?php
$client = $this->client;
?>
<h1>Plánování</h1>
<h2><?php echo $client->company_name, ", ", $client->headquarters_town, ", ", $client->headquarters_street; ?></h2>
<table class="multirow-table">
    <thead>
        <tr>
            <th colspan="4">Pobočka</th>
        </tr>
        <tr>
            <th>Provedené dohlídky</th>
            <th>Naplánované dohlídky</th>
            <th>Počet dohlídek</th>
            <th>Prověrka</th>
        </tr>
    </thead>
<?php
foreach ($this->progress as $item) {
    ?>
    <tbody>
        <tr>
            <td colspan="4"><?php 
            // vytvoreni url a vypsani jmena pobocky
            $url = $this->url(array("clientId" => $client->id_client, "subsidiaryId" => $item->id_subsidiary), "planning-subsidiary");
            printf("<a href='%s'>%s, %s, %s</a>", $url, $item->subsidiary_name, $item->subsidiary_town, $item->subsidiary_street); 
            ?></td>
        </tr>
        <tr>
            <td>
                <ol>
                    <?php
                    if (isset($this->watchIndex[$item->id_subsidiary])) {
                        foreach ($this->watchIndex[$item->id_subsidiary] as $watch) {
                            // vygenerovani URL
                            $url = $this->url(array("clientId" => $watch->client_id, "subsidiaryId" => $watch->subsidiary_id, "watchId" => $watch->id), "audit-watch-get");

                            printf("<li><a href='%s'>%s</a></li>", $url, $watch->watched_at);
                        }
                    }
                    ?>
                </ol>
            </td>
            <td>Zatím neimplementováno</td>
            <td><?php echo $item->watches_done, "/", $item->watches_count ? $item->watches_count : "0"; ?></td>
            <td><?php 
            // vyhodnoceni, zda je proveden audit nebo proverka
            if ($item->audits_done) {
                $isDone = "Ano";

                // pokud je k dispozici zaznam o auditu nebo proverce, pak se vytvori odkaz (logicky by k dispozici mel byt, ale jen pro jistotu)
                if (isset($this->auditIndex[$item->id_subsidiary])) {
                    $audit = $this->auditIndex[$item->id_subsidiary];
                    $url = $this->url(array("clientId" => $audit->client_id, "subsidiaryId" => $audit->subsidiary_id, "auditId" => $audit->id), "audit-get");

                    $isDone = sprintf("<a href='%s'>Ano</a>", $url);
                }
            } else {
                $isDone = "Ne";
            }
            echo $isDone; 
            ?></td>
        </tr>
    </tbody>
    <?php
}
?>
</table>