<?php echo $this->selectForm;?>
<?php if ($this->subsidiaryId != null){?>

<div class="box">
	<?php if($this->canCreateWorkplace){?><a class="large" href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId), 'workplaceNew'); ?>">Přidat pracoviště</a>
	| <?php } if ($this->canCreateFolder){?><a class="large show-folder-form">Umístění pracoviště - přidat nové</a>
	| <?php } if ($this->canDeleteFolder){?><a class="large show-folder-delete">Smazat umístění</a>
	| <?php } if($this->filter == 'vse'){?> 
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'neuplna'), 'workplaceList'); ?>">Vyfiltrovat neúplná pracoviště</a>
	<?php }else{?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'vse'), 'workplaceList'); ?>">Zobrazit všechna pracoviště</a>
	<?php }?>
</div>

<div class="hidden box folder-form">
	<?php echo $this->textForm; ?>
</div>

<div class="hidden box folder-delete">
	<?php echo $this->deleteForm; ?>
</div>
<div>

<?php if($this->workplaces != null){
	$folder = 'default';
	foreach($this->workplaces as $workplace){
		if($workplace['folder'] != $folder){
			$folder = $workplace['folder']; ?>
			</div><h3><?php
				if($folder == ''){
					echo 'Pracoviště bez určeného umístění';
				}
				else{
					echo $folder;
				}
			?>
			</h3>
			<div class="box">
		<?php } ?>
		<div>
			&bull; <a class="show-info workplace-title"><?php echo $workplace['workplace']->getName()?></a>
			<?php if($this->canEditWorkplace){?>| <a href="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'workplaceId' => $workplace['workplace']->getIdWorkplace()), 'workplaceEdit');?>">Editovat</a>
			<?php }if($this->canDeleteWorkplace){?>| <form class="inline" action="<?php echo $this->url(array('clientId' => $this->clientId, 'subsidiaryId' => $this->subsidiaryId, 'workplaceId' => $workplace['workplace']->getIdWorkplace()), 'workplaceDelete') ?>" method="post"><input class="button-anchor" type="submit" value="Smazat" onclick="return confirm('Opravdu si přejete smazat toto pracoviště?')" /></form>
			<?php }if($this->canSwitchFolder){?>| <?php echo $this->folderSwitch($workplace['workplace']->getIdWorkplace())?>
		<?php }?></div>
		<div class="workplace-info hidden">
			<?php if($workplace['workplace']->getBusinessHours()){?>
				<p class="no-margin"><span class="bold">Provozní doba: </span> <?php echo $workplace['workplace']->getBusinessHours()?></p>
			<?php }?>
			<?php if($workplace['workplace']->getDescription()){?>
				<p class="no-margin"><span class="bold">Popis: </span> <?php echo $workplace['workplace']->getDescription()?></p>
			<?php }?>
			<?php if($workplace['workplace']->getRisks()){?>
				<p class="no-margin"><span class="bold">Rizika: </span> <?php echo $workplace['workplace']->getRisks()?></p>
			<?php }?>
			<?php if($workplace['workplace']->getRiskNote()){?>
				<p class="no-margin"><span class="bold">Poznámka k rizikům: </span> <?php echo $workplace['workplace']->getRiskNote()?></p>
			<?php }?>
			<?php if($this->canViewPrivate){
				if($workplace['workplace']->getRiskPrivate()){?>
				<p class="no-margin"><span class="bold">Soukromá poznámka k rizikům: </span> <?php echo $workplace['workplace']->getRiskPrivate()?></p>
			<?php }}?>
			<?php if($workplace['workplace']->getBossSurname()){?>
				<p class="no-margin"><span class="bold">Vedoucí pracoviště: </span> <?php echo $workplace['workplace']->getBossName() . ' ' . $workplace['workplace']->getBossSurname();
								if ($workplace['workplace']->getBossPhone()){
									echo ', telefon: ' . $workplace['workplace']->getBossPhone();
								}
								if ($workplace['workplace']->getBossEmail()){
									echo ', e-mail: ' . $workplace['workplace']->getBossEmail();
								}?></p>
			<?php }?>
			<?php if($workplace['workplace']->getNote()){?>
				<p class="no-margin"><span class="bold">Poznámka: </span> <?php echo $workplace['workplace']->getNote()?></p>
			<?php }?>
			<?php if($this->canViewPrivate){
				if($workplace['workplace']->getPrivate()){?>
				<p class="no-margin"><span class="bold">Soukromá poznámka: </span> <?php echo $workplace['workplace']->getPrivate()?></p>
			<?php }}?>
			<?php if(isset($workplace['positions'])){?>
				<p class="no-margin"><span class="bold">Pracovní pozice na pracovišti: </span></p>
				<ul class="no-margin-bottom">
				<?php foreach($workplace['positions'] as $position){?>
					<li><?php echo $position?></li>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($workplace['works'])){?>
				<p class="no-margin"><span class="bold">Pracovní činnosti na pracovišti: </span></p>
				<ul class="no-margin-bottom">
				<?php foreach($workplace['works'] as $work){?>
					<li><?php echo $work?></li>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($workplace['technical_devices'])){?>
				<p class="no-margin"><span class="bold">Technické prostředky na pracovišti: </span></p>
				<ul class="no-margin-bottom">
				<?php foreach($workplace['technical_devices'] as $technicalDevice){?>
					<li><?php if ($technicalDevice['sort']){
						echo $technicalDevice['sort'];
					}?>
					<?php if ($technicalDevice['sort'] && $technicalDevice['type']){
						echo ' ';
					}?>
					<?php if ($technicalDevice['type']){
						echo $technicalDevice['type'];
					}?></li>
				<?php }?>
				</ul>
			<?php }?>
			<?php if(isset($workplace['chemicals'])){?>
				<p class="no-margin"><span class="bold">Chemické látky na pracovišti: </span></p>
				<ul class="no-margin-bottom">
				<?php foreach($workplace['chemicals'] as $chemical){?>
					<li><?php echo $chemical['chemical']?></li>
					<?php if ($chemical['usual_amount']){ ?>
						<li class="no-bullet"><span class="bold">Obvyklé množství: </span><?php echo $chemical['usual_amount'];?></li>
					<?php }?>
					<?php if ($chemical['use_purpose']){ ?>
						<li class="no-bullet"><span class="bold">Účel použití: </span><?php echo $chemical['use_purpose'];?></li>
					<?php }?>					
				<?php }?>
				</ul>
			<?php }?>
		</div>
	<?php } ?></div>
<?php } else {
		if ($this->filter == "vse"){?>
	<p>Pobočka nemá žádná pracoviště.</p>
	<?php }else{?>
	<p>Pobočka nemá žádná neúplná pracoviště.</p>
	<?php }?>
<?php }?>

<?php }?>