<p>Pokyny pro vyplnění:</p>
<p>pracovištěm je rozuměno vnitřní nebo venkovní prostor pro práci, který je stavebně nebo jinak oddělen: zámečnická dílna, prodejna, venkovní sklad, příruční sklad... Není nutné, aby se zde trvale vyskytovali zaměstnanci.</p>
<p>Tento formulář je třeba vyplnit, navazuje na něj formulář 'pracovní pozice', jehož výstupem je databáze pracovišť.</p>
<p><em><strong>Pro nápovědu k vyplňování podržte kurzor myši nad otazníkem.</strong></em></p>
<?php echo $this->form; ?>

<div class="hidden">
	<div id="new_position_form">
	<?php echo $this->formPosition; ?>
	</div>
</div>

<div class="hidden">
	<div id="new_employee_form">
	<?php echo $this->formEmployee; ?>
	</div>
</div>

<div class="hidden">
	<div id="new_work_form">
	<?php echo $this->formWork; ?>
	</div>
</div>