<?php echo $this->render('header.phtml') ?>

<div class="clear">
    <div id="upper-panel">
        <?php 
        $this->navigation()->findHelper("menu")->setUlClass("common-menu");
        echo $this->navigation()->menu()->renderMenu(Zend_Registry::get("UpperPanel"));
        $this->navigation()->findHelper("menu")->setUlClass("");
        ?>
    </div>
    <span class="icon-home">
        <a href="/" title="Go home"></a>
    </span>
    <div id="cnt-identification">
        <span id="client-name">
            <?php echo $this->clientInfo();?>
        </span>
        <span id="client-risks">
            Úroveň rizika&nbsp;&nbsp;<span class="big"><?php echo $this->clientRisk() * 1; ?></span>
        </span>
    </div><br class="clear">
<div class="span-5 border navigation">
	<?php $clientNav = Zend_Registry::get('ClientNavigation'); ?>
	<?php echo $this->navigation()->menu()->renderMenu($clientNav); ?>
</div>

<div class="push-1 span-19 main-content">
	<?php echo $this->messages(); ?>
	<h2><?php echo $this->subtitle; ?></h2>
	<?php echo $this->layout()->content; ?>
</div>
</div>

<?php echo $this->render('footer.phtml')?>