<?php
$this->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html;charset=utf-8' );
$this->headTitle ()->setSeparator ( ' - ' );
$this->headTitle ( 'Guardian' );
echo $this->doctype ();
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headMeta (); ?>
<?php echo $this->headTitle (); ?>

<?php $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'), 'screen, projection'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/ie.css'), 'screen, projection', 'IE');?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/print.css'), 'print'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/global.css'), 'screen, projection'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui-1.8.21.custom.css'), 'screen, projection');?>
<?php $this->headLink()->appendStylesheet($this->baseUrl("css/questionary.css"), 'screen'); ?>

<?php $this->headScript()->appendFile($this->baseUrl('js/jquery-1.7.2.min.js'), 'text/javascript');?>
<?php $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-1.8.21.custom.min.js'), 'text/javascript');?>
<?php $this->headScript()->appendFile($this->baseUrl('js/application.js'), 'text/javascript')
							 ->prependScript('BASE_URL = "' . $this->baseUrl() . '";');?>
<?php $this->headScript()->appendFile($this->baseUrl('js/jquery.jec-1.3.4.js'), 'text/javascript');?>

<?php echo $this->headLink()?>
<?php echo $this->headScript()?>
</head>

<body>
	<div class="container" style="width: 600px">
			<div class="push-1 span-19 main-content" style="width: 590px">
			<?php echo $this->layout()->content; ?>
						</div>
		</div>
	</div>
</body>
</html>