<?php
$this->headMeta ()->appendHttpEquiv ( 'Content-Type', 'text/html;charset=utf-8' );
$this->headTitle ()->setSeparator ( ' - ' );
$this->headTitle ( 'Guardian' );
echo $this->doctype ();
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headMeta (); ?>
	<?php echo $this->headTitle (); ?>
	
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'), 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/ie.css'), 'screen, projection', 'IE');?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/print.css'), 'print'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/global.css'), 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('/css/jquery-ui-1.10.1.custom.css'), 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl("css/questionary.css"), 'screen'); ?>
	
	<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery-1.9.1.js'), 'text/javascript'); ?>
	<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery-ui-1.10.1.custom.min.js'), 'text/javascript'); ?>
	<?php $this->headScript()->appendFile($this->baseUrl('js/application.js'), 'text/javascript')
							 ->prependScript('BASE_URL = "' . $this->baseUrl() . '";');?>
	<?php $this->headScript()->appendFile($this->baseUrl('js/ajaxCheckboxes.js'), 'text/javascript')
							 ->prependScript('BASE_URL = "' . $this->baseUrl() . '";');?>
	<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.jec-1.3.4.js'), 'text/javascript');
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.validate.pack.js'), 'text/javascript');
	?>
		
	<?php echo $this->headLink()?>
	<?php echo $this->headScript()?>
</head>

<body>
	<div class="container">
		<div id="header" class="prepend-top"><div id="logged-in-as" class="push-20 last span-4"><?php echo $this->loggedInAs(); ?></div>
		<h1 class="span-19 pull-3 border"><?php echo "Guardian"; ?></h1></div>