<?php echo $this->render('header.phtml') ?>
<hr class="redline" />
<div class="clear">
    <div id="upper-panel">
        <?php 
        $this->navigation()->findHelper("menu")->setUlClass("common-menu");
        echo $this->navigation()->menu()->renderMenu(Zend_Registry::get("UpperPanel"));
        $this->navigation()->findHelper("menu")->setUlClass("");
        ?>
    </div>
<div id="left-menu">
		<?php echo $this->navigation()->menu(); ?>
</div>

<div class="push-1 span-19 main-content">
	<?php echo $this->messages(); ?>
	<h2><?php echo $this->subtitle; ?></h2>
	<?php echo $this->layout()->content; ?>
</div>
</div>
<?php echo $this->render('footer.phtml')?>