<h3>
	Pobočka: <?php echo $this->subsidiary->getSubsidiaryName();?>
</h3>

<div class="box clear" id="pobocky">
	<?php echo $this->form;?>
	<?php if ($this->canViewHeadquarters){?>
	<a href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientIndex')?>">Zpět na kartu klienta</a>
	<?php }?>
</div>

<div class="box overflow span-11" id="informations">
		<?php echo $this->subsidiary();?>
	</div>

<div class="span-5 overflow push-1 box width-200"><h3>Hodnota rizika pobočky</h3>
<p>*****</p></div>
	
<div class="box clear">
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientAdmin')?>">Administrace</a>
	 | <a class="large" href="#">Pracovní pozice</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiary->getIdSubsidiary()), 'workplaceList')?>">Pracoviště</a>
	 | <a class="large" href="#">Pracovní činnosti</a>
</div>

<div class="box tasks clear">
	<h3>Osobní úkoly</h3>
	<p>neshody nebo lhůty, u kterých je zadáno jméno - přiděluje KOO popřípadě KL, Při auditu se vyplní pouze G7 nebo KL.</p>
</div>

<div class="box">
	<h3>Bezpečnostní deník</h3>
	<p>dodělat okno pro psaní zpráv a odesílání souborů</p>
	<?php echo $this->formFilter;?>
	<?php echo $this->formSearch;?>
	<div class="overflow"><?php echo $this->diary();?></div>
	<hr/>
	<p><a class="messages-link">Poslat zprávu/soubor</a></p>
	<div class="hidden" id="zpravy"><?php echo $this->formMessages; ?></div>
</div>

<div class="box deadlines">
	<h3>Termíny a lhůty</h3>
	<p>NESHODY a LHŮTNÍKY nastavené je filtrování podle termínu. Celkový přehled o blížících se a propadlých termínech. Možnost hypertext se prokliknout na kartu KL, kterém neshoda nebo lhůta náleží.
	</p>
</div>