<?php 
$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();
?>
<div class="box">
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientIndex')?>">Zpět na centrálu</a>
	<?php if($this->subsidiary['subsidiary']->getActive()){?>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiary' => $this->subsidiary['subsidiary']->getIdSubsidiary()), 'subsidiaryEdit')?>">Editovat pobočku</a>
	 <?php }?>
</div>

<div class="box overflow span-11" id="informations">
		<?php echo $this->subsidiary();?>
	</div>

<div class="span-5 overflow push-1 box width-200"><h3>Hodnota rizika pobočky</h3>
<p><center><big><strong><?php echo $this->riskScore ? $this->riskScore : 0; ?></strong></big></center></p></div>
<?php 
// pokud se jedna pouze o sidlo, nebude se dal ve vypisech pokracovat
if ($this->subsidiary['subsidiary']->getHqOnly()) return;
?>
<div class="box clear">
<?php if(!$this->archived && $this->subsidiary['subsidiary']->getActive() ){
	if ($user->role != My_Role::ROLE_CLIENT) {
	?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientAdmin')?>">Administrace</a>
	 | <?php }?><a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiary['subsidiary']->getIdSubsidiary(), 'filter' => 'vse'), 'positionList')?>">Pracovní pozice</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiary['subsidiary']->getIdSubsidiary(), 'filter' => 'vse'), 'workplaceList')?>">Pracoviště</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiary['subsidiary']->getIdSubsidiary(), 'filter' => 'podle-pracovist'), 'workList')?>">Pracovní činnosti</a>
	 | 
	 <?php } ?>
	 <a class='large' href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiary['subsidiary']->getIdSubsidiary()), "audit-list"); ?>">Audity</a>
	 |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiary['subsidiary']->getIdSubsidiary()), "deadline-index"); ?>">Lhůty</a>
	 |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiary["subsidiary"]->getIdSubsidiary()), "audit-watch-index"); ?>">Dohlídky</a>
	 |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient()), "document-documentation-index") . "?subId=" . $this->subsidiary['subsidiary']->getIdSubsidiary(); ?>">Dokumentace</a>
	 |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiary['subsidiary']->getIdSubsidiary()), "audit-mistakes-index-subs"); ?>">Neshody</a>
</div>

<?php 
if ($acl->isAllowed($user->role, "task", "index")) {
?>
<div class="box tasks">
	<h3>Osobní úkoly</h3>
	<?php 
	echo $this->action("index", "task", null, array("subsidiaryId" => $this->subsidiary['subsidiary']->getIdSubsidiary()));
	?>
</div>

<?php 
}
?>

<div>
	<h3>Bezpečnostní deník</h3>
	<p>dodělat okno pro psaní zpráv a odesílání souborů</p>
	<?php echo $this->formFilter;?>
	<?php echo $this->formSearch;?>
	<div class="overflow"><?php echo $this->diary();?></div>
	<hr/>
	<h2>Poslat zprávu</h2>
	<p class="bold">Zde můžete zaslat zprávu do bezpečnostního deníku této pobočky:</p>
	<div id="zpravy" class="subsidiary-messages"><?php echo $this->formMessages; ?></div>
</div>

<div class="box deadlines">
	<h3>Termíny a lhůty</h3>
	<?php 
	$acl = new My_Controller_Helper_Acl();
	$user = Zend_Auth::getInstance()->getIdentity();
	
	$config = array("name" => "Jméno/Zařízení");
	
	if ($acl->isAllowed($user->role, "deadline:deadline", "edit")) {
		$config["buttons"] = array("edit" => array("caption" => "Upravit", "type" => "button"));
	}
	
	echo $this->formHidden("CLIENT_ID", $this->client->getIdClient());
	echo $this->deadlineTable($this->invalidDeadlines, $config);
	echo "<script type='text/javascript' src='/js/deadline/deadline.js'></script>";
	?>
	<p>NESHODY a LHŮTNÍKY nastavené je filtrování podle termínu. Celkový přehled o blížících se a propadlých termínech. Možnost hypertext se prokliknout na kartu KL, kterém neshoda nebo lhůta náleží.
	</p>
</div>