<ul>
<?php foreach ($this->subsidiaries as $subsidiary){?>
	<li>
		<a href="<?php echo $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex')?>">
			<?php echo $subsidiary->getSubsidiaryName() . ', ' . $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown();?>
		<?php if(!$subsidiary->getActive()){
			echo ' (neaktivní)';
		}?>
		</a>
	</li>
<?php } ?>
</ul>