<?php
echo "<div class='box'>" . $this->docMenu() . "</div>";

$file = $this->file;
$versions = $this->versions;
$current = $versions[$versions->count() - 1];
$loaded = $this->loaded;

// vyhodnoceni verze
$type = ($current->id == $loaded->id) ? "Aktuální verze" : "Stará verze";
?>
<h1>Dokument</h1>
<h2><?php echo $this->file()->fileName($this->file) . " - " . $type; ?></h2>
<?php 
// vypocet velikosti dokumentu
$unit = "B";
$size = (int) $current->size;

if ($size > 1024) {
	$size = round($size / 1024, 2);
	$unit = "K";
}

if ($size > 1024) {
	$size = round($size / 1024, 2);
	$unit = "M";
}

$acl = new My_Controller_Helper_Acl();
$editButton = "";
$user = Zend_Auth::getInstance()->getIdentity();
$editable = $acl->isAllowed($user->role, "document:document", "editother") || $file->user_id == $user->id_user;

// kontrola opravneni
if ($editable) $editButton = $this->formButton("rename-file", "Přejmenovat");
?>
<table>
	<tr>
		<td>Jméno souboru</td>
		<td><?php echo $this->file()->fileName($file); echo " " . $editButton; ?></td>
	</tr>
	<?php 
	if ($this->documentations->count()) {
		?>
	<tr>
		<td>
		Dokumentace
		</td>
		<td>
		<?php 
		foreach ($this->documentations as $item) {
			// zjisteni jmena pobocky a vygenerovani adresy na dokumentace
			$subName = $item->subsidiary_name ? $item->subsidiary_name : "CENTRÁLNÍ";
			$baseUrl = $this->url(array("clientId" => $item->client_id, "TYPE" => "documentation", "subsidiaryId" => $item->subsidiary_id), "document-documentation-index");
			$url = sprintf("%s?subId=%s", $baseUrl, $item->subsidiary_id);
			
			$name = sprintf("<a href='%s'>%s</a>", $url, $subName);
			
			printf("%s<br />", $name);
		}
		?>
		</td>
	</tr>
		<?php 
	}
	?>
</table>
<p>
	<strong><big><?php echo $this->version()->download($loaded); ?></big></strong>
</p>
<?php 
if ($editable) {
?>
<h2>Nahrát aktualizaci</h2>
<?php 
	echo $this->uploadForm; 
}
?><br />
<h2>Historie verzí</h2>
<ol>
<?php 
foreach ($versions as $version) {
	echo "<li>";
	echo ($version->id == $loaded->id) ? $this->version()->date($version->created_at) : $this->version($version);
	echo "</li>";
}
?>
</ol>
<h2>Adresáře</h2>
<ul>
<?php 
$clientId = Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId", 0);

foreach ($this->directories as $directory) {
	// url pro detach
	$url = $this->url(array("clientId" => $clientId, "fileId" => $file->id, "directoryId" => $directory->id), "document-dettach");
	
	echo "<li>";
	
	if ($editable) echo "<a href='$url' class='dettach'>Odebrat z adresáře</a>";
	
	echo $this->path($directory->path(), $directory, true);
	echo "</li>";
}
?>
</ul>
<?php 
if ($acl->isAllowed($user->role, "document:document", "editother"))
	echo $this->formButton("attach-dir", "Přidat do adresáře"); 
?>
<div id="rename-form" class="hidden">
<?php echo $this->renameForm; ?>
</div>
<div id="attach-form" class="hidden">
<?php 
if ($acl->isAllowed($user->role, "document:document", "editother")) {
// vygenerovani seznamu korenovych adresaru
$roots = array("0" => "---Vyberte klienta---");

foreach ($this->roots as $root) {
	$roots[$root->id] = $root->name;
}

echo $this->formSelect("root-list", 0, null, $roots);
?>
	<div id="attach-path"></div>
	<form action="<?php echo $this->url(array("clientId" => Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId", 0), "fileId" => $file->id), "document-attach"); ?>" method="post" id="form-attach">
		<div>
			Vybraný adresář: <strong id="attach-selected"></strong>
			<input type="hidden" name="directoryId" value="0" id="dirId" />
			<input type="submit" value="Připojit" disabled="disabled" id="attach-submit" />
		</div>
	</form>
	<ul id="attach-content" style="list-style: none;"></ul>
</div>
<?php 
}
?>
<script type="text/javascript" src="/js/document/document.js"></script>