<?php if ($this->deleted){ ?>

	<p>Klient <em><?php echo $this->companyName ?></em> neexistuje. Pravděpodobně byl smazán.</p>
	
<?php } else {?>

<p><span class="bold">Název klienta: </span><?php echo $this->companyName;?></p>
<a href="<?php echo $this->url(array('clientId' => $this->clientId), 'clientIndex') ?>">Zpět na kartu klienta</a><br/><br/>
<table>
	<tr>
		<td colspan=4><a href="<?php echo $this->url(array('clientId' => $this->clientId), 'clientEdit') ?>">EDITACE ZÁKLADNÍCH ÚDAJŮ</a></td>
	</tr>
	<tr>
		<td><a href="#">PŘIDAT PRACOVIŠTĚ</a></td>
		<td colspan=2><a href="#">EDITACE</a></td>
		<td><a href="#">UPLOAD</a></td>
	</tr>
	<tr>
		<td><a href="#">PŘIDAT PRACOVNÍ POZICE</a></td>
		<td colspan=2><a href="#">EDITACE</a></td>
		<td><a href="#">UPLOAD</a></td>
	</tr>
	<tr>
		<td><a href="#">PŘIDAT ODPOVĚDNÉ OSOBY</a></td>
		<td colspan=3><a href="#">EDITACE</a></td>
	</tr>
	<tr>
		<td><a href="<?php echo $this->url(array('clientId' => $this->clientId), 'subsidiaryNew') ?>">PŘIDAT POBOČKU</a></td>
		<td><a class="edit-link">EDITACE</a></td>
		<td><a class="delete-link">SMAZAT</a></td>
		<td></td>
	</tr>
</table>
<?php if ($this->canDeleteClient){ ?>
<form id="smazat" action="<?php echo $this->url(array('clientId' =>$this->clientId), 'clientDelete')?>" method="post"><input class="anchor" type="submit" value="SMAZAT KLIENTA" onclick="return confirm('Opravdu chcete klienta smazat?')"/></form>
<?php }?>

<div id="pobocky" class="hidden">
		<?php echo $this->form; ?>
</div>

<h3>Provést audit</h3>
<ul>
	<li><a href="#">Systémový audit</a></li>
	<li><a href="#">Kontrola pracovišť</a></li>
</ul>

<?php } ?>