<?php if ($this->deleted){ ?>

	<p>Klient <em><?php echo $this->companyName ?></em> neexistuje. Pravděpodobně byl smazán.</p>
	
<?php } else {?>

<p><span class="bold">Název klienta: </span><?php echo $this->companyName;?></p>
<?php if ($this->canViewHeadquarters){?>
	<a href="<?php echo $this->url(array('clientId' => $this->clientId), 'clientIndex') ?>">Zpět na kartu klienta</a><br/><br/>
<?php }?>
<table>
<?php if ($this->canViewHeadquarters){?>
	<tr>
		<td colspan=4><a href="<?php echo $this->url(array('clientId' => $this->clientId), 'clientEdit') ?>">EDITACE ZÁKLADNÍCH ÚDAJŮ</a></td>
	</tr>
<?php }?>
	<tr>
		<td>
			<?php if ($this->canAddSubsidiary){?>
			<a href="<?php echo $this->url(array('clientId' => $this->clientId), 'subsidiaryNew') ?>">PŘIDAT POBOČKU</a>
			<?php } else {?>
			POBOČKY
			<?php }?>
		</td>
		<td><a class="edit-subsidiary-link">EDITACE</a></td>
		<td>
			<?php if ($this->canDeleteSubsidiary){?>
			<a class="delete-subsidiary-link">SMAZAT</a>
			<?php }?>
		</td>
		<td></td>
	</tr>
</table>
<form id="archivovat" action="<?php echo $this->url(array('clientId' => $this->clientId), 'clientArchive')?>" method="post"><input class="anchor" type="submit" value="PŘESUNOUT KLIENTA DO ARCHIVU"/></form>
<?php if ($this->canDeleteClient){ ?>
<form id="smazat" action="<?php echo $this->url(array('clientId' =>$this->clientId), 'clientDelete')?>" method="post"><input class="anchor" type="submit" value="SMAZAT KLIENTA" onclick="return confirm('Opravdu chcete klienta smazat?')"/></form>
<?php }?>

<div id="pobocky" class="hidden">
		<?php echo $this->form; ?>
</div>

<h3>Provést audit</h3>
<ul>
	<li><a href="#">Systémový audit</a></li>
	<li><a href="#">Kontrola pracovišť</a></li>
</ul>

<?php } ?>