<?php echo $this->filters()?>

<div class="box" id="filtered">

<?php 
$alphabet = '';
$list = '';

$list .= '<br/><br/><a name="up"></a><a href="#down">&#x25BC; Dolů &#x25BC;</a>';

$client = "";
$companyName = "";
$companyAddress = "";
$clientId = "";
$allowed = "";
$initial = "";

$list .= '<ul>';

foreach ($this->subsidiaries as $subsidiary) :
	if($subsidiary->getHq()){
		$list .= '</ul>';		
		$firstLetter = ucfirst(mb_substr($subsidiary->getSubsidiaryName(), 0, 1, 'utf-8'));
		if ($firstLetter != $initial){
			if($firstLetter == 'C' && $initial != '' && $initial != 'A' && $initial != 'B'){
				$initial = 'Ch';
			} else if ($firstLetter == 'C' && $initial == 'Ch') {
				;
			} else {
				$initial = $firstLetter;
			}
			$alphabet .= '<a href="#' . $initial . '">' . $initial . '</a> ';
			$list .= '<a class="letter" name="' . $initial . '">' . $initial . '</a>';
		}
		$companyName = $subsidiary->getSubsidiaryName();
		$companyAddress = $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown();
		$allowed = $subsidiary->getAllowed();
	}
	if($subsidiary->getAllowed()){
		if ($clientId != $subsidiary->getClientId()){
			
			$clientId = $subsidiary->getClientId();
			
			$list .= '<p class="bold concealer">';
			
			if($allowed){
				$list .= '<a>';
			}
			$list .= '<span class="anchor">' . $companyName . ' - ' . $companyAddress . '</span>';
			if($allowed){
				$list .= '</a>';
			}
			$list .= '</p><ul class="hidden">';
			if ($allowed){
				$list .= '<li><a href="' . $this->url(array('clientId' => $clientId), 'clientIndex') . '">' . $companyName . ' - ' . $companyAddress . ' (centrála)</a>';
				$allowed = '';
			}
			if(!$subsidiary->getHq()){
				$list .= '<li><a href="' . $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex') . '">' . $subsidiary->getSubsidiaryName() . ' - ' . $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown() . '</a></li>';
			}
		}
		else{
			$list .= '<li><a href="' . $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex') . '">' . $subsidiary->getSubsidiaryName() . ' - ' . $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown() . '</a></li>';
		}
	}
endforeach;
$list .= '</ul><a name="down"></a><a href="#up">&#x25B2; Nahoru &#x25B2;</a>';

echo $alphabet;
echo $list;
?>	
</div>