<?php echo $this->filters($this->archived)?>

<div class="box" id="filtered">
<a name="up"></a>
<a href="#down">&#x25BC; Dolů &#x25BC;</a>
	<?php $assigned = ""; ?>
	<ul>
	<?php foreach ($this->subsidiaries as $subs) :
	$subsidiary = $subs['subsidiary'];
	if($subsidiary->getHqOnly()){
		continue;
	}
	if($subsidiary->getAllowed()){
		if ($assigned != $subs['username']){?>
			</ul>
			<?php $assigned = $subs['username']; ?>
			<p class="bold"><?php echo $assigned; ?></p>
			<ul>
		<?php }
		if ($subsidiary->getHq()) {?>
			<li class="bold"><a href="<?php echo $this->url(array('clientId' => $subsidiary->getClientId()), 'clientIndex');?>">
				<?php echo $subsidiary->getSubsidiaryName() . ' (centrála)'?>
			</a></li>
		<?php }
		else {?>
			<li><?php echo '<a href="' . $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex') . '">' . $subsidiary->getSubsidiaryName() . ' - ' . $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown();
			if(!$subsidiary->getActive()){
				echo ' (neaktivní)';
			}
			echo '</a>'?></li>
		<?php }
	}
		endforeach; ?>
	</ul>
	<a name="down"></a>
<a href="#up">&#x25B2; Nahoru &#x25B2;</a>		
</div>