<div class="box" id="pobocky">
		<?php echo $this->form; ?>
</div>

<div class="box overflow span-12" id="informations">
		<?php echo $this->client();?>
</div>	

<div class="span-5 floating-box"><h3>Hodnota rizika u klienta</h3>
<p>*****</p></div>

<div class="span-5 floating-box">
<?php if(!$this->archived){?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientAdmin')?>">Edituj klienta</a>
	<?php }else{?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientRecover')?>">Obnovit klienta z archivu</a>
	<?php }?>
</div>

<div class="box clear">
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'vse'), 'positionList')?>">Pracovní pozice</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'vse'), 'workplaceList')?>">Pracoviště</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'podle-pracovist'), 'workList')?>">Pracovní činnosti</a>
	 <?php if ($this->createAuditAllowed) { ?>
	 | <a href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiaryId), "audit-create"); ?>">Provést audit</a>
	 <?php } ?>
</div>

<div class="box tasks">
	<h3>Osobní úkoly</h3>
	<p>neshody nebo lhůty, u kterých je zadáno jméno - přiděluje KOO popřípadě KL, Při auditu se vyplní pouze G7 nebo KL.</p>
</div>

<div class="box">
	<h3>Bezpečnostní deník</h3>
	<p>dodělat okno pro psaní zpráv a odesílání souborů</p>
	<?php echo $this->formFilter;?>
	<?php echo $this->formSearch;?>
	<div class="overflow"><?php echo $this->diary();?></div>
	<hr/>
	<p class="bold">Zde můžete zaslat zprávu do bezpečnostního deníku zvolených poboček:</p>
	<div id="zpravy"><?php echo $this->formMessages; ?></div>
</div>

<div class="box deadlines">
	<h3>Termíny a lhůty</h3>
	<p>NESHODY a LHŮTNÍKY nastavené je filtrování podle termínu. Celkový přehled o blížících se a propadlých termínech. Možnost hypertext se prokliknout na kartu KL, kterém neshoda nebo lhůta náleží.
	</p>
</div>