<?php 
$acl = new My_Controller_Helper_Acl();
$user = Zend_Auth::getInstance()->getIdentity();

printf("<script type='text/javascript'>var SUBSIDIARY_ID = %s</script>", $this->subsidiaryId);
?>
<div class="box" id="pobocky">
		<?php echo $this->form; ?>
</div>

<div class="box overflow span-12" id="informations">
		<?php echo $this->client();?>
</div>	

<div class="span-5 floating-box"><h3 style="margin-top: 0px;" title="součet závažností všech neodstraněných neshod">Hodnota rizika u klienta</h3>
<div><center><big><strong><?php echo $this->riskScore ? $this->riskScore : 0; ?></strong></big></center></div></div>

<div class="span-5 floating-box"><h3 style="margin-top: 0px;">G U A R D 7, v.o.s.</h3>
<strong>Adresa</strong>: Divišova 235. 530 03 Pardubice<br />
<strong>Telefon</strong>: 466 535 700<br />
<strong>Email</strong>: guardian@guard7.cz
</div>
<div class="span-5 floating-box">
<?php if(!$this->archived){?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientAdmin')?>">Edituj klienta</a>
	<?php }else{?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient()), 'clientRecover')?>">Obnovit klienta z archivu</a>
	<?php }?>
</div>
<?php 
// pokud se jedna pouze o sidlo, nebude se dal ve vypisech pokracovat
if ($this->subsidiary['subsidiary']->getHqOnly()) return;
?>
<div class="box clear">
<?php 
if ($user->role != My_Role::ROLE_CLIENT) {
?>
	<a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'vse'), 'positionList')?>">Pracovní pozice</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'vse'), 'workplaceList')?>">Pracoviště</a>
	 | <a class="large" href="<?php echo $this->url(array('clientId' => $this->client->getIdClient(), 'subsidiaryId' => $this->subsidiaryId, 'filter' => 'podle-pracovist'), 'workList')?>">Pracovní činnosti</a>
	 | <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiary['subsidiary']->getIdSubsidiary()), "deadline-index"); ?>">Lhůty</a>
     | <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiary['subsidiary']->getIdSubsidiary()), "audit-mistakes-index-subs"); ?>">Neshody</a>
	 | 
	 <?php } ?>
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "subsidiaryId" => $this->subsidiaryId), "audit-list"); ?>">Audity</a>
	 |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient()), "audit-watch-index-client"); ?>">Dohlídky</a>
	 |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "TYPE" => "documentation", "subId" => $this->subsidiaryId), "document-documentation-index"); ?>">Dokumentace</a>
     |
	 <a class="large" href="<?php echo $this->url(array("clientId" => $this->client->getIdClient(), "TYPE" => "record", "subId" => $this->subsidiaryId), "document-documentation-index"); ?>">Záznamy</a>
</div>

<?php 
// pokud se jedna o klienta, pak se zobrazi vypisy neshod a lhut
if ($user->role == My_Role::ROLE_CLIENT) {
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $request->setParam("subsidiaryId", $this->subsidiaryId);
    $params = $request->getParams();
    $params["subsidiaryId"] = $this->subsidiaryId;
    
    echo "<h3 id='deadlines'>Lhůty</h3>";
    printf("<fieldset><legend>Nová lhůta</legend>%s</fieldset>",
            $this->formButton("new-deadline", "Přidat novou lhůtu")
    );
    
    echo $this->action("all", "index", "deadline", $params);
    
    $request->setParam("subsidiaryId", null);
    
    echo "<h3 id='mistakes'>Neshody</h3>";
    echo $this->action("index", "mistake", "audit", $params);
    
    return;
}

if ($acl->isAllowed($user->role, "task", "index")) {
?>
<div class="box tasks">
	<h3>Osobní úkoly</h3>
	<?php 
	echo $this->action("index", "task", null, array("subsidiaryId" => $this->subsidiaryId));
	?>
</div>

<?php 
}
?>

<div>
	<h3>Bezpečnostní deník</h3>
	<p>dodělat okno pro psaní zpráv a odesílání souborů</p>
	<?php echo $this->formFilter;?>
	<?php echo $this->formSearch;?>
	<div class="overflow"><?php echo $this->diary();?></div>
	<hr/>
	<h2>Poslat zprávu</h2>
	<p class="bold">Zde můžete zaslat zprávu do bezpečnostního deníku zvolených poboček:</p>
	<div id="zpravy"><?php echo $this->formMessages; ?></div>
</div>

<div class="box deadlines">
	<h3>Termíny a lhůty</h3>
	<?php 
	$acl = new My_Controller_Helper_Acl();
	$user = Zend_Auth::getInstance()->getIdentity();
	
	$config = array("name" => "Jméno/Zařízení");
	
	if ($acl->isAllowed($user->role, "deadline:deadline", "edit")) {
		$config["buttons"] = array("edit" => array("caption" => "Upravit", "type" => "button"));
	}
	
	echo $this->formHidden("CLIENT_ID", $this->client->getIdClient());
	echo $this->deadlineTable($this->invalidDeadlines, $config);
	echo "<script type='text/javascript' src='/js/deadline/deadline.js'></script>"; 
	?>
	<p>NESHODY a LHŮTNÍKY nastavené je filtrování podle termínu. Celkový přehled o blížících se a propadlých termínech. Možnost hypertext se prokliknout na kartu KL, kterém neshoda nebo lhůta náleží.
	</p>
</div>