<?php echo $this->filters()?>

<div class="box" id="filtered">

	<?php $client = "";
	$companyName = "";
	$companyAddress = "";
	$clientId = "";
	$allowed = ""?>
	<ul>
	<?php foreach ($this->subsidiaries as $subsidiary) :
	if($subsidiary->getHq()){
		if($allowed){ ?>
		</ul>
		<p class="bold">
			<a href="<?php echo $this->url(array('clientId' => $clientId), 'clientIndex')?>"><?php echo $companyName; ?> - <?php echo $companyAddress; ?></a>
		</p>
		<ul>
		<?php }
		$companyName = $subsidiary->getSubsidiaryName();
		$companyAddress = $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown();
		$clientId = $subsidiary->getClientId();
		$allowed = $subsidiary->getAllowed();
		continue;
	}
	if($subsidiary->getAllowed()){
		if ($client != $subsidiary->getClientId()){?>
			</ul>
			<?php $client = $subsidiary->getClientId(); ?>
			<p class="bold">
			<?php if($allowed){?><a href="<?php echo $this->url(array('clientId' => $clientId), 'clientIndex')?>"><?php }?>
				<?php echo $companyName . ' - ' . $companyAddress ?>
			<?php if($allowed){?></a><?php
				$allowed = ''; }?>
			</p>
			<ul>
		<?php } ?>
		<li><?php echo '<a href="' . $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex') . '">' . $subsidiary->getSubsidiaryName() . '</a>'?></li>
	<?php }
		endforeach; ?>
	</ul>
	
	
		
	
</div>