<?php echo $this->filters($this->archived)?>

<div class="box" id="filtered">
<a name="up"></a>
<a href="#down">&#x25BC; Dolů &#x25BC;</a>

	<?php $client = "";
	$companyName = "";
	$companyAddress = "";
	$clientId = "";
	$allowed = ""?>
	<ul>
	<?php if(count($this->subsidiaries)){ 
	foreach ($this->subsidiaries as $subsidiary) :
	if($subsidiary->getHq()){
		$companyName = $subsidiary->getSubsidiaryName();
		$companyAddress = $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown();
		$allowed = $subsidiary->getAllowed();
	}
	if($subsidiary->getAllowed()){
		if ($clientId != $subsidiary->getClientId()){?>
			</ul>
			<?php $clientId = $subsidiary->getClientId(); ?>
			<p class="bold concealer">
			<?php if($allowed){?><a><?php }?>
				<span class="anchor"><?php echo $companyName . ' - ' . $companyAddress ?></span>
			<?php if($allowed){?></a><?php }?>
			</p>
			<ul class="hidden">
			<?php if ($allowed){
			echo '<li><a href="' . $this->url(array('clientId' => $clientId), 'clientIndex') . '">' . $companyName . ' - ' . $companyAddress . ' (centrála)</a>';
			$allowed = ''; }
			if(!$subsidiary->getHq()){?>
			<li><?php echo '<a href="' . $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex') . '">' . $subsidiary->getSubsidiaryName() . ' - ' . $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown() . '</a>'?></li>
		<?php }}
		else{ ?>
		<li><?php echo '<a href="' . $this->url(array('clientId' => $subsidiary->getClientId(), 'subsidiary' => $subsidiary->getIdSubsidiary()), 'subsidiaryIndex') . '">' . $subsidiary->getSubsidiaryName() . ' - ' . $subsidiary->getSubsidiaryStreet() . ', ' . $subsidiary->getSubsidiaryTown() . '</a>'?></li>
		<?php }?>
	<?php }
		endforeach;
	}
	else{
		echo '<p>V archivu nejsou momentálně žádní klienti.</p>';
	} ?>
	</ul>	
	
<a name="down"></a>
<a href="#up">&#x25B2; Nahoru &#x25B2;</a>		
	
</div>