<div class="box overflow span-11">
		<?php echo $this->client();?>
	</div>

	

<div class="box span-5 append-1"><h3>Hodnota rizika u klienta</h3>
<p>*****</p></div>

<div class="box span-5 append-1">
		<a href="<?php echo $this->url(array('clientId' => $this->client['id_client']), 'clientAdmin')?>">Edituj</a> | <a href="#">Vyber pobočku</a>
	</div>

<div class="box tasks clear">
	<h3>Osobní úkoly</h3>
	<p>neshody nebo lhůty, u kterých je zadáno jméno - přiděluje KOO popřípadě KL, Při auditu se vyplní pouze G7 nebo KL.</p>
</div>

<div class="box">
	<h3>Bezpečnostní deník</h3>
	<p>dodělat okno pro psaní zpráv a odesílání souborů</p>
	<div class="diary"><?php echo $this->diary();?></div>
</div>

<div class="box deadlines">
	<h3>Termíny a lhůty</h3>
	<p>NESHODY a LHŮTNÍKY nastavené je filtrování podle termínu. Celkový přehled o blížících se a propadlých termínech. Možnost hypertext se prokliknout na kartu KL, kterém neshoda nebo lhůta náleží.
	</p>
</div>