<table border="1" cellpadding="2">
	<thead>
		<tr>
			<td valign="middle" align="center">
			Závada
			</td>
			<td valign="middle" align="center">
			Odpovědná<br />osoba
			</td>
			<td valign="middle" align="center">
			Datum<br />zjištění
			</td>
			<td valign="middle" align="center">
			Termín<br />odstranění
			</td>
			<td valign="middle" align="center">
			Splněno
			</td>
			<td valign="middle" align="center">
			Poznámka
			</td>
		</tr>
	</thead>
	<tbody>
	<?php 
	foreach ($this->mistakes as $mistake) {
		?>
		<tr>
			<td>
			<?php echo $mistake->mistake; ?>
			</td>
			<td>
			<?php echo $mistake->responsibile_name; ?>
			</td>
			<td>
			<?php echo $this->sqlDate($mistake->notified_at); ?>
			</td>
			<td>
			<?php echo $mistake->removed_at ? $this->sqlDate($mistake->removed_at) : "-"; ?>
			</td>
			<td>
			<?php echo $mistake->is_removed ? "ANO" : "NE"; ?>
			</td>
			<td>
			<?php echo $mistake->comment; ?>
			</td>
		</tr>
		<?php 
	}
	?>
	</tbody>
</table>