<h1 align="center">Protokol z kontrolní dohlídky</h1>
<table>
	<tr>
		<td>
		<strong>Ve společnosti</strong>
		</td>
		<td>
		<?php echo $this->client->company_name; ?>
		</td>
	</tr>
	<tr>
		<td>
		<strong>Provozovna</strong>
		</td>
		<td>
		<?php echo sprintf("%s, %s", $this->subsidiary->subsidiary_street, $this->subsidiary->subsidiary_town); ?>
		</td>
	</tr>
	<tr>
		<td>
		<strong>Dne</strong>
		</td>
		<td>
		<?php echo $this->sqlDate($this->watch->watched_at); ?>
		</td>
	</tr>
</table>&nbsp;<br />&nbsp;<br />&nbsp;
<table border="1" cellpadding="5">
	<tr>
		<td>
		Provedl
		</td>
		<td>
		<?php echo $this->user->name; ?>
		</td>
	</tr>
	<?php 
	if ($this->watch->other_guard) {
		?>
	<tr>
		<td>
		Dále se za G U A R D 7, v.o.s. zúčastnil
		</td>
		<td>
		<?php echo $this->watch->other_guard; ?>
		</td>
	</tr>
		<?php 
	}
	?>
	<tr>
		<td>
		Čas
		</td>
		<td>
		<?php echo substr($this->watch->time_from, 0, 5) . " - " . substr($this->watch->time_to, 0, 5); ?>
		</td>
	</tr>
	<tr>
		<td>
		Zástupce klienta
		</td>
		<td>
		<?php echo $this->person->name; ?>
		</td>
	</tr>
	<tr>
		<td>
		E-mail
		</td>
		<td>
		<?php echo $this->person->email; ?>
		</td>
	</tr>
	<tr>
		<td>
		Telefon
		</td>
		<td>
		<?php echo $this->person->phone; ?>
		</td>
	</tr>
	<?php 
	if ($this->watch->other_client) {
		?>
	<tr>
		<td>
		Dále se za klienta zúčastnil
		</td>
		<td>
		<?php echo $this->watch->other_client; ?>
		</td>
	</tr>
		<?php 
	}
	?>
</table>
<?php 
return;
// pokud nebyl soubezne proveden audit, pak se vypisi neshody a lhuty
if (!$this->watch->also_audit) {
	// rozrazeni neshod na nove, odstranene a neodstranene
	$new = array();
	$removed = array();
	$marked = array();
	$watch = $this->watch;
	
	foreach ($this->mistakes as $mistake) {
		// vyhodnoceni neshody
		if ($mistake->set_removed) {
			$removed[] = $mistake;
		} elseif ($mistake->watch_id == $watch->id) {
			$new[] = $mistake;
		} else {
			$marked[] = $mistake;
		}
	}
	
	// nove neshody
    if ($new) {
        ?>
        <h2>Nově nalezené neshody</h2>
        <?php 

        if ($new) {
            echo $this->partial("watch/_mistakes.phtml", array("mistakes" => $new, "columns" => array("mistake" => "Neshoda", "weight" => "Závažnost", "suggestion" => "Návrh opatření", "responsibile_name" => "Odpovědná osoba", "will_be_removed_at" => "Navrhovaný termín odstranění")));
        } else {
            echo "<div>-</div>";
        }
    }
	
	// vyhodnoceni zobrazeni neodstranenych neshod
	if ($watch->display_mistakes && $marked) {
		?>
		<h2>Neodstraněné neshody z minulých kontrol</h2>
		<?php 
		if ($marked) {
			echo $this->partial("watch/_mistakes.phtml", array("mistakes" => $marked, "columns" => array("mistake" => "Neshoda", "weight" => "Závažnost", "notified_at" => "Datum zjištění", "suggestion" => "Návrh řešení", "responsibile_name" => "Odpovědná osoba", "will_be_removed_at" => "Navrhovaný termín odstranění")));
		} else {
			echo "<div>-</div>";
		}
	}
	
	// vyhodnoceni zobrazeni lhut lhuty se zobrazi pokud je zobrazeni nastaveno a pokud jsou nejake lhuty k dispozici
	if ($watch->display_deadlines && $this->deadlines->count()) {
	?>
	<h2>Propadlé lhůty</h2>
	<table border="1" cellpadding="2">
		<?php 
		$config = array("noAction" => true, "headBg" => "#c6c6c6", "subsidiaryRow" => false);
		echo $this->deadlineTable()->header($config);
		echo implode("", $this->deadlineTable()->deadlines($this->deadlines, $config));
		?>
	</table>
	<?php
	}
}
?>
