<h2>Nová neshoda k dohlídce</h2>
<?php
// odkaz zpet
$watch = $this->watch;
$url = $this->url(array("watchId" => $watch->id, "clientId" => $watch->client_id, "subsidiaryId" => $watch->subsidiary_id), "audit-watch-edit");

echo "<a href='$url'>Zpět na dohlídku</a>";

echo $this->form;

$this->headScript()->appendFile("/js/audit/watch.js");
$this->headScript()->appendFile("/js/audit/mistake/create.js");
?>