<?php
$this->layout()->setLayout("floating-layout");

$options = array(
		"buttons" => array(
            "show" => array(
						"type" => "button",
						"caption" => "Zobrazit",
						"url" => "/deadline/deadline/get?deadlineId=%deadlineId&clientId=%clientId&__retLink=1"
						),
    
				"edit" => array(
						"type" => "button",
						"caption" => "Editovat",
						"url" => "/deadline/deadline/edit?deadlineId=%deadlineId&clientId=%clientId&__retLink=1"
						)
				)
		);

echo $this->deadlineTable($this->deadlines, $options);
?>
<script type="text/javascript">
$(function() {
    $("#deadlinetable button").click(function () {
        window.location.href = $(this).attr("g7:url");
    })
});
</script>
