<?php
$this->layout()->setLayout("floating-layout");

$options = array(
		"buttons" => array(
				"deadlineId[]" => array(
						"type" => "checkbox",
						"caption" => "Přidat"
						),
				
				"edit" => array(
						"type" => "link",
						"caption" => "Editovat",
						"url" => "/deadline/deadline/edit?deadlineId=%deadlineId&clientId=%clientId&__retLink=1"
						)
				)
		);
?>
<form action="<?php printf("/audit/watch/adddead.html?watchId=%s", $this->watch->id); ?>" method="post">
<?php 
echo $this->deadlineTable($this->deadlines, $options);
echo $this->formSubmit("submit", "Vybrat");
?>
</form>
