<div id="watch-tabs">
	<ul>
		<li><a href="#tab-overview">Přehled</a></li>
		<li><a href="#tab-discuss">Provedeno</a></li>
		<?php 
		if (!$this->watch->also_audit) {
		?>
		<li><a href="#tab-mistakes">Neshody</a></li>
		<li><a href="#tab-deadlines">Lhůty</a></li>
		<?php 
		}
		?>
		<li><a href="#tab-changes">Změny</a></li>
		<li><a href="#tab-orders">Objednávky</a></li>
		<li><a href="#tab-outputs">Realizační výstup</a></li>
	</ul>
	<div id="tab-overview">
		<h1>Dohlídka</h1>
		<?php
		$watch = $this->watch;
		
		echo $this->form;
		
		$url = "/audit/watch/protocol.pdf";
		
		echo "<form action='/audit/watch/send' method='get'>" .
				$this->formHidden("watchId", $watch->id) . $this->formSubmit("protocol", "Odeslat návrh protokolu") . "</form>";
		
		echo "<br />";
		
		echo "<form action='$url' target='_blank' method='get'>" . 
			$this->formHidden("watchId", $watch->id) . $this->formSubmit("protocol", "Náhled protokolu") . "</form>";
		
		$url = "/audit/watch/submit?watchId=" . $this->watch->id;
		
		echo "<br/><br/><p><a onclick=\"return confirm('Skutečně uzavřít dohlídku?')\" href='$url' id='close-watch'>Uzavřít dohlídku</a></p>"
		?>
		<div id="other-contact-person">
		<h2>Jiný zástupce klienta</h2>
		<?php 
		echo $this->contactForm;
		?>
		</div>
	</div>
	<div id="tab-discuss">
		<form action="/audit/watch/discuss" method="post" id="form-discuss">
			<ol id="discuss-list">
			<?php 
			foreach ($this->discussed as $item) {
				echo "<li>";
				echo $this->formTextarea("discussed[content][]", $item->content, array("rows" => 4, "cols" => 50));
				echo $this->formButton("discussed-$item->id-delete", "Smazat");
				echo "</li>";
			}
			?>
			</ol>
			<div>
			<?php 
			echo $this->formHidden("watchId", $this->watch->id);
			echo $this->formSubmit("discuss-submit", "Uložit");
			echo $this->formButton("add-discuss", "Přidat položku");
			?>
			</div>
		</form>
	</div>
	<div id="tab-changes">
		<form action="/audit/watch/changes" method="post" id="form-changes">
			<ol id="change-list">
			<?php 
			foreach ($this->changes as $item) {
				echo "<li>";
				echo $this->formTextarea("change[content][]", $item->content, array("rows" => 4, "cols" => 50));
				echo $this->formButton("change-$item->id-delete", "Smazat");
				echo "</li>";
			}
			?>
			</ol>
			<div>
			<?php 
			echo $this->formHidden("watchId", $this->watch->id);
			echo $this->formSubmit("change-submit", "Uložit");
			echo $this->formButton("add-change", "Přidat položku");
			?>
			</div>
		</form>
	</div>
<?php 
if (!$this->watch->also_audit) {
?>
	<div id="tab-mistakes">
		<h2>Nová neshoda</h2>
		<?php 
		$url = "/audit/watch/createmistake?watchId=$watch->id&clientId=$watch->client_id&subsidiary_id=$watch->subsidiary_id";
		?>
		<form action="<?php echo $url; ?>" method="post">
			<table>
				<tr>
					<td>
					<?php echo $this->formLabel("mistake-workplace_id", "Pracoviště"); ?>
					</td>
					<td>
					<?php 
					// zpracovani pobocek
					$workplaces = array("0" => "--- MIMO PRACOVIŠTĚ ---");
					
					foreach ($this->workplaces as $item) {
						$workplaces[$item->id_workplace] = $item->name;
					}
					
					echo $this->formSelect("workplaceId", null, array(), $workplaces);
					?>
					</td>
				</tr>
				<tr>
					<td colspan="2">
					<?php echo $this->formSubmit("mistake-new", "Nová neshoda"); ?>
					</td>
				</tr>
			</table>
		</form>
		<h2>Neshody</h2>
		<form action="/audit/watch/mistakes?watchId=<?php echo $this->watch->id; ?>" method="post">
			<em>Vyberte neshody, které budou označeny jako odstraněné</em>
			<table class="multirow-table" id="mistakes">
			<?php 
			echo $this->mistakeTable()->header();
			$params = array("selector" => true, "actions" => array("edit" => "Upravit", "get" => "Zobrazit"));
			
			foreach ($this->mistakes as $mistake) {
				// vyhodnoceni, zda je neshoda kriticka
				if ($mistake->set_removed) {
					$params["classes"] = array("mistake-removed");
				} elseif ($mistake->is_marked)
					$params["classes"] = array("mistake-marked");
				else
					$params["classes"] = array();
				
				echo $this->mistakeTable()->mistake($mistake, $params);
			}
			?>
			</table>
			<p>
			<?php 
			echo $this->formSubmit("mistake-remove", "Označit jako odstraněné"); 
			echo $this->formSubmit("mistake-unremove", "Označit jako NEodstraněné");
			?>
			</p>
		</form>
	</div>
	<div id="tab-deadlines">
		<?php 
		echo "<p>";
		echo $this->formButton("new-deadline", "Zobrazit/skrýt novou lhůtu");
		echo "</p>";
		echo "<div id='deadlineform-container' style='display: none;'>";
		echo $this->action("create.html", "deadline", "deadline", Zend_Controller_Front::getInstance()->getRequest()->getParams());
		echo "</div>";
		
		$options = array(
				"buttons" => array(
						"show" => array(
								"caption" => "Zobrazit",
								"type" => "button"
								),
						"edit" => array(
								"caption" => "Editovat",
								"type" => "button"
								),
						"selected[]" => array(
								"caption" => "Vybrat",
								"type" => "checkbox"
								)
						)
				);
		
		$options["form"] = array(
				"action" => "/audit/watch/subdead?watchId=" . $watch->id
				);
		
		echo $this->deadlineTable($this->deadlines, $options);
		echo $this->formButton("add-deadlines", "Zkontrolovat ostatní lhůty");
		?>
	</div>
<?php 
}
?>
	<div id="tab-orders">
		<form action="/audit/watch/orders" method="post" id="form-orders">
			<ol id="order-list">
			<?php 
			foreach ($this->orders as $item) {
				echo "<li>";
				echo $this->formTextarea("order[content][]", $item->content, array("rows" => 4, "cols" => 50));
				echo $this->formButton("order-$item->id-delete", "Smazat");
				echo "</li>";
			}
			?>
			</ol>
			<div>
			<?php 
			echo $this->formHidden("watchId", $this->watch->id);
			echo $this->formSubmit("order-submit", "Uložit");
			echo $this->formButton("add-order", "Přidat položku");
			?>
			</div>
		</form>
	</div>
	<div id="tab-outputs">
		<form action="/audit/watch/outputs" method="post" id="form-output">
			<?php echo $this->formTextarea("outputs", $watch->outputs, array("style" => "height: 10em; width: 80%; ")); ?>
			<div>
			<?php 
			echo $this->formHidden("watchId", $this->watch->id);
			echo $this->formSubmit("output-submit", "Uložit");
			?>
			</div>
		</form>
	</div>
</div>
<script type="text/javascript" src="/js/audit/watch.js"></script>
<?php 
echo $this->formHidden("CLIENTID", Zend_Controller_Front::getInstance()->getRequest()->getParam("clientId")); 
echo $this->formHidden("WATCHID", $this->watch->id);
?>
