<?php 
$client = $this->client;
$audit = $this->audit;

$url = $this->url(array("clientId" => $client->id_client, "auditId" => $audit->id, "subsidiaryId" => $audit->subsidiary_id), "audit-edit");
?>
<h1>Výstupní zpráva auditu</h1>
<?php 
echo "<a href='$url'>Zpět na audit</a>";
$address = $client->headquarters_street . ", " . $client->headquarters_town . ", " . $client->headquarters_code;

if ($audit->is_check) {
	$name = "Zpráva o provedení roční prověrky bezpečnosti práce a požární ochrany";
	$progresNoteCaption = "Cíl roční prověrky BOZP a PO";
	$progresCaption = "Průběh roční prověrky BOZP a PO";
	
} else {
	$name = "Zpráva o provedení auditu bezpečnosti práce a požární ochrany";
	$progresNoteCaption = "Cíl auditu BOZP a PO";
	$progresCaption = "Průběh auditu BOZP a PO";
	
}

$address = sprintf("%s, %s, %s", $this->subsidiary->subsidiary_town, $this->subsidiary->subsidiary_street, $this->subsidiary->subsidiary_code);

if ($this->hq->id_subsidiary == $this->subsidiary->id_subsidiary) {
	$hqAddress = $address;
} else {
	$hqAddress = sprintf("%s, %s, %s", $this->hq->subsidiary_town, $this->hq->subsidiary_street, $this->hq->subsidiary_code);
}

$opts = array(
		"deadlines" => $this->deadlines,
    "deadlinesClose" => $this->deadlinesClose,
		"common" => array(
				"name" => $name,
				"org" => $client->company_name,
				"org_hq" => $hqAddress,
				"ico" => $client->company_number,
				"sub_hq" => $address,
				"done_at" => $audit->done_at,
				"done_in" => $address,
				"auditor_name" => $this->auditor->name,
				"contact_name" => ($this->contact ? $this->contact->name : $audit->contact_name),
				"progres_note_caption" => $progresNoteCaption,
				"progres_caption" => $progresCaption,
				"progress_note" => $audit->progress_note,
				"summary" => $audit->summary
		),
		
		"forms" => array(
				"list" => $this->forms,
				"groups" => $this->formsGroups
		),
		
		"progresItems" => $audit->getProgres(),
		
		"workplaces" => $this->workplaces,
		
		"mistakes" => $this->mistakes,
		
		"client" => $this->client,
		"audit" => $this->audit
);

echo $this->partial("report/_form.phtml", $opts);
?>