<?php 
$audit = $this->audit;

printf("<a href='%s'>Zpět na audit</a>", $this->url(array("clientId" => $audit->client_id, "subsidiaryId" => $audit->subsidiary_id, "auditId" => $audit->id), "audit-get"));
$common = $this->report->toArray();

$opts = array(
		"common" => $this->report->toArray(),

		"forms" => array(
				"list" => $this->forms,
				"groups" => $this->formsGroups
		),

		"progresItems" => $this->items,

		"workplaces" => $this->workplaces,

		"mistakes" => $this->mistakes,

		"client" => $this->client,
		"audit" => $this->audit
);

printf("<h2>%s</h2>", $common["name"]);

$url = $this->url(array("auditId" => $this->audit->id, "clientId" => $this->audit->client_id, "subsidiaryId" => $this->audit->subsidiary_id), "audit-report-download");
echo "<div class='box' align='center'><form style='float: left;' action='$url' method='post' target='_blank' id='download-form'><input type='submit' value='Otevřít ve formátu PDF'></form>";

if (Zend_Auth::getInstance()->getIdentity()->role != My_Role::ROLE_CLIENT) {
    $url2 = sprintf("/audit/report/send?auditId=%s", $audit->id);

    echo "<form action='$url2' method='post' id='send-form' style='float: right;'><input type='submit' value='Odeslat kontaktní osobě emailem'></form>";
}

echo "<br style='clear: both;' /></div>";
?>
<menu id="up-menu">
	<li><a href="#common">Obecné informace</a></li>
	<li><a href="#target">Cíl a průběh auditu</a></li>
	<li><a href="#summary">Zjištění z auditu</a></li>
	<li><a href="#forms">Systematická část</a></li>
	<li><a href="#workplaces">Vyhodnocení pracovišť</a></li>
	<li><a href="#mistakes">Registr neshod</a></li>
</menu>
<fieldset>
    <legend id="common">
        <small>[<a href="#up-menu">Nahoru</a>]
        </small> Obecné informace
    </legend>
    <table>
        <tbody>
            <tr>
                <td>Organizace</td>
                <td><?php echo $common["org"]; ?>
                </td>
            </tr>
            <tr>
                <td>Sídlem</td>
                <td><?php echo $common["org_hq"]; ?>
                </td>
            </tr>
            <tr>
                <td>IČO</td>
                <td><?php echo $common["ico"]; ?>
                </td>
            </tr>
            <?php 
if ($common["sub_hq"] != $common["org_hq"]) {
            ?>
            <tr>
                <td>Provozovna se sídlem</td>
                <td><?php echo $common["sub_hq"]; ?>
                </td>
            </tr>
            <?php 
}
            ?>
            <tr>
                <td>Datum provedení</td>
                <td><?php echo $common["done_at"]; ?>
                </td>
            </tr>
            <tr>
                <td>Místo provedení</td>
                <td><?php echo $common["done_in"]; ?>
                </td>
            </tr>
            <tr>
                <td>Provedl</td>
                <td><?php echo $common["auditor_name"]; ?>
                </td>
            </tr>
            <tr>
                <td>Účastníci za klienta</td>
                <td><?php echo $common["contact_name"]; ?>
                </td>
            </tr>
        </tbody>
    </table>
</fieldset>
<fieldset>
    <legend id="target">
        <small>[<a href="#up-menu">Nahoru</a>]
        </small> Cíl a průběh auditu
    </legend>
    <?php 
    printf("<h3>%s</h3>", $common["progres_note_caption"]); 
    printf("<div style='white-space: pre'>%s</div>", $audit["progress_note"]);
    printf("<h3>%s</h3>", $common["progres_caption"]);

    echo "<ol>";

    $i = 0;

    foreach ($this->items as $item) {
        echo "<li>";
        echo $item->content;
        echo "</li>";

        $i++;
    }

    echo "</ol>";
    ?>
</fieldset>
<fieldset>
    <legend id="summary">
        <small>[<a href="#up-menu">Nahoru</a>]
        </small> Zjištění z auditu
    </legend>
    <?php 
    printf("<div style='white-space: pre-line'>%s</div>", $audit["summary"]); 
    ?>
</fieldset>
<fieldset>
    <legend id="forms">
        <small>[<a href="#up-menu">Nahoru</a>]
        </small> Systematická část
    </legend>
    <?php 
    foreach ($this->forms as $form) {
        $formId = $form["id"];
        $groups = $this->formsGroups[$formId];
        ?>
    <h2>
        <?php echo $form["name"]; ?>
    </h2>
    <div id="<?php echo "chart-$formId"; ?>"></div>
    <table class="report" id="frm-<?php echo $formId; ?>">
        <tbody>
            <?php 
            for ($i = 0; $i < count($groups["groups"]); $i++) {
                $group = $groups["groups"][$i];

                if (!isset($groups["groupsInfo"][$group["id"]])) continue;

                $points = $groups["groupsInfo"][$group["id"]];

                if (!$points["max"]) continue;

                $percent = (1 - $points["gained"] / $points["max"]) * 100;
                $percent = round($percent);
                ?>
            <tr>
                <td><?php echo $i + 1; ?></td>
                <td><?php echo $group["name"]; ?></td>
                <td class="report-percent"><?php echo $percent; ?>%</td>
            </tr>
            <?php 
            }
            ?>
        </tbody>
    </table>
    <?php 
    }
    ?>
</fieldset>
<fieldset>
    <legend id="workplaces"><small>[<a href="#up-menu">Nahoru</a>] </small> Vyhodnocení pracovišť</legend>
    <?php 
    // vypsani navigace v pracovistich
    echo "<menu>\n";

    foreach ($this->workplaces["workplaces"] as $workplace) {
        echo "<li><a href='#work-" . $workplace["id_workplace"] . "'>" . $workplace["name"] . "</a></li>\n";
    }

    echo "</menu>\n";

    $commentIndex = $this->workplaces["comments"];

    // odkaz vracejici na navigaci
    $return = "<small>[<a href='#workplaces'>Nahoru</a>]</small>";

    foreach ($this->workplaces["workplaces"] as $workplace) {
        $id = $workplace["id_workplace"];

        echo "<hr />";
        echo "<h2 id='work-$id'>" . $workplace["name"] . "</h2>\n";
        echo $return;
        ?>
    <h3>Komentář</h3>
    <?php
        // vyhodnoceni jestli je komentar nastaven 
        $filled = isset($commentIndex[$id]);

        if ($filled) $filled = !empty($commentIndex[$id]["comment"]);

        if ($filled) {
            echo "<pre>" . $commentIndex[$id]["comment"] . "</pre>";
        } else {
            echo "<em>Žádný komentář nebyl nastaven</em>";
        }
    ?>
    <h3>Neshody</h3>
    <?php 
        if (isset($this->workplaces["mistakes"][$id])) {
            ?>
    <table>
        <thead>
            <tr>
                <th>Závažnost</th>
                <th>Neshoda</th>
                <th>Navrhované opatření</th>
                <th>Komentář</th>
            </tr>
        </thead>
        <tbody>
        <?php 
        foreach ($this->workplaces["mistakes"][$id] as $mistake) {
            ?>
            <tr>
                <td><?php echo $mistake["weight"]; ?></td>
                <td class="pre"><?php echo $mistake["mistake"]; ?></td>
                <td class="pre"><?php echo $mistake["suggestion"]; ?></td>
                <td class="pre"><?php echo $mistake["comment"]; ?></td>
            </tr>
            <?php 
        }
        ?>
        </tbody>
    </table>
            <?php 
        } else {
            echo "<em>Na tomto pracovišti nebyly zjištěny žádné neshody</em>";
        }
    ?>
        <?php 
    }
    ?>
</fieldset>
<fieldset>
    <legend id="mistakes"><small>[<a href="#up-menu">Nahoru</a>] </small> Registr neshod</legend>
    <?php 
    foreach ($this->forms as $form) {
        echo "<h2>" . $form["name"] . "</h2>";

        // zpracovani skupin
        $formId = $form["id"];
        $groups = $this->formsGroups[$formId];

        for ($i = 0; $i < count($groups["groups"]); $i++) {
            // vyhodnoceni jestli je nejaka neshoda v teto skupine
            $group = $groups["groups"][$i];

            if (!isset($this->mistakes["forms"][$group["id"]])) continue;

            echo "<h3>" .($i + 1) . ". " . $group["name"] . "</h3>";

            ?>
    <table>
        <thead>
            <tr>
                <th>Závažnost</th>
                <th>Neshoda</th>
                <th>Navrhované opatření</th>
                <th>Komentář</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            foreach ($this->mistakes["forms"][$group["id"]] as $mistake) {
                ?>
                <tr>
                    <td><?php echo $mistake["weight"]; ?></td>
                    <td class="pre"><?php echo $mistake["mistake"]; ?></td>
                    <td class="pre"><?php echo $mistake["suggestion"]; ?></td>
                <td class="pre"><?php echo $mistake["comment"]; ?></td>
            </tr>
                <?php 
            }
            ?>
        </tbody>
    </table>
            <?php 
        }
    }
    // rozdeleni neshod dle stavu
        $new = array();
        $removed = array();
        $old = array();
        
        foreach ($this->mistakes["others"] as $mistake) {
            switch ($mistake["status"]) {
                case 0:
                    $old[] = $mistake;
                    break;
                    
                case 1:
                    $new[] = $mistake;
                    break;
                    
                case 2:
                    $removed[] = $mistake;
                    break;
            }
        }
		?>
		<h2>Ostatní neshody</h2>
		<?php 
		if (empty($this->mistakes["others"])) {
			echo "<em>Nejsou žádné další neshody";
		} else {
            // nove neshody
            if ($new) {
            ?>
        <h3>Nové neshody</h3>
            <table>
                <thead>
                    <tr>
                        <th>Závažnost</th>
                        <th>Neshoda</th>
                        <th>Navrhované opatření</th>
                        <th>Komentář</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach ($new as $mistake) {
                        ?>
                        <tr>
                            <td><?php echo $mistake["weight"]; ?></td>
                            <td class="pre"><?php echo $mistake["mistake"]; ?></td>
                            <td class="pre"><?php echo $mistake["suggestion"]; ?></td>
                            <td class="pre"><?php echo $mistake["comment"]; ?></td>
                    </tr>
                        <?php 
                    }
                    ?>
                </tbody>
            </table>
            <?php
            }
            
            // stavajici neshody
            if ($old) {
            ?>
        <h3>Stávající neodstraněné neshody</h3>
            <table>
                <thead>
                    <tr>
                        <th>Závažnost</th>
                        <th>Neshoda</th>
                        <th>Navrhované opatření</th>
                        <th>Komentář</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach ($old as $mistake) {
                        ?>
                        <tr>
                            <td><?php echo $mistake["weight"]; ?></td>
                            <td class="pre"><?php echo $mistake["mistake"]; ?></td>
                            <td class="pre"><?php echo $mistake["suggestion"]; ?></td>
                            <td class="pre"><?php echo $mistake["comment"]; ?></td>
                    </tr>
                        <?php 
                    }
                    ?>
                </tbody>
            </table>
            <?php
            }
            
            // nove neshody
            if ($removed) {
            ?>
        <h3>Odstraněné neshody</h3>
            <table>
                <thead>
                    <tr>
                        <th>Závažnost</th>
                        <th>Neshoda</th>
                        <th>Navrhované opatření</th>
                        <th>Komentář</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    foreach ($removed as $mistake) {
                        ?>
                        <tr>
                            <td><?php echo $mistake["weight"]; ?></td>
                            <td class="pre"><?php echo $mistake["mistake"]; ?></td>
                            <td class="pre"><?php echo $mistake["suggestion"]; ?></td>
                            <td class="pre"><?php echo $mistake["comment"]; ?></td>
                    </tr>
                        <?php 
                    }
                    ?>
                </tbody>
            </table>
            <?php
            }
		}
		?>
</fieldset>
<?php if ($this->deadlines->count() || $this->deadlinesClose->count()) { ?>
	<fieldset>
		<legend id="deadlines">Lhůty</legend>
		<?php 
        if ($this->deadlines->count()) {
            echo "<h2>Propadlé lhůty</h2>";
            echo $this->deadlineTable($this->deadlines, array("noAction" => true, "subsidiaryRow" => false));
        }
        
        if ($this->deadlinesClose->count()) {
            echo "<h2>Lhůty před propadnutím</h2>";
            echo $this->deadlineTable($this->deadlinesClose, array("noAction" => true, "subsidiaryRow" => false));
        }
		?>
	</fieldset>
    <?php } ?>
<script type="text/javascript" src="/js/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="/js/jqplot.barRenderer.min.js"></script>
<script type="text/javascript" src="/js/jqplot.toImage.js"></script>
<script type="text/javascript" src="/js/audit/report/report.js"></script>
